#!/usr/bin/env bash
set -euo pipefail

# Load .env
if [ -f .env ]; then
  set -a; source .env; set +a
fi

# ── Data-plane topology ──────────────────────────────────────────────────────
# Headscale carries its embedded DERP relay on its own listener, and a reverse
# proxy cannot carry DERP (long-lived non-WebSocket upgrade + UDP STUN). There
# are therefore exactly two working topologies:
#
#   1. TLS mode  — HEADSCALE_TLS_HOSTNAME set. Headscale terminates TLS on 443
#      itself and relays through its embedded DERP. No proxy in front of it.
#      This is the setup validated end-to-end (Pi + phone on 5G/CGNAT).
#   2. Proxy mode — Headscale behind Caddy/Cloudflare Tunnel, WITH a standalone
#      derper (DERP_HOSTNAME) on a public host providing the relay.
#
# Anything else leaves CGNAT clients unable to connect, so it is refused below.
COMPOSE_FILES=(-f docker-compose.yml)
TLS_MODE=0

if [ -n "${HEADSCALE_TLS_HOSTNAME:-}" ]; then
  TLS_MODE=1
  COMPOSE_FILES+=(-f docker-compose.tls.yml)

  EXPECTED_URL="https://${HEADSCALE_TLS_HOSTNAME}"
  if [ "${HEADSCALE_EXTERNAL_URL:-}" != "$EXPECTED_URL" ]; then
    echo "ERROR: TLS mode expects HEADSCALE_EXTERNAL_URL=${EXPECTED_URL}" >&2
    echo "       (currently: ${HEADSCALE_EXTERNAL_URL:-unset})" >&2
    echo "       Agents join the mesh at that URL — it must match the certificate." >&2
    exit 1
  fi

  echo "Headscale: native TLS on 443 for ${HEADSCALE_TLS_HOSTNAME} (no proxy)."

  # Without this, a bare `docker compose up` silently brings Headscale back on
  # plain 8080 — a different topology from the one deploy.sh just built, and one
  # where nothing answers on 443. Setting COMPOSE_FILE in .env makes every
  # docker compose command in this directory include the overlay.
  if [ -f .env ] && ! grep -q '^COMPOSE_FILE=' .env; then
    echo 'COMPOSE_FILE=docker-compose.yml:docker-compose.tls.yml' >> .env
    echo "  Note: COMPOSE_FILE ajouté à .env — les commandes docker compose"
    echo "        directes incluront désormais l'overlay TLS."
  fi
  echo "  Required: 443/tcp + 3478/udp forwarded to this host, and the DNS"
  echo "  record resolving DIRECTLY (Cloudflare: DNS-only, grey cloud)."
  if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
    echo "  Note: the tunnel carries web + API only. Do NOT add a tunnel route"
    echo "        for ${HEADSCALE_TLS_HOSTNAME} — it would break DERP and ACME."
  fi
fi

# Generate cloudflared local config from CLOUDFLARE_TUNNEL_TOKEN
# Cloudflare Tunnel → Caddy (HTTP/1.1) → services
# Caddy handles WebSocket Upgrade natively (required for Headscale TS2021)
if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
  mkdir -p cloudflared
  python3 - <<'PY'
import base64, json, os
from urllib.parse import urlparse

def host(url):
    p = urlparse(url)
    return p.netloc if p.netloc else url

token = os.environ['CLOUDFLARE_TUNNEL_TOKEN']
padding = (4 - len(token) % 4) % 4
data = json.loads(base64.b64decode(token + '=' * padding).decode())

with open('cloudflared/creds.json', 'w') as f:
    json.dump({'AccountTag': data['a'], 'TunnelID': data['t'], 'TunnelSecret': data['s']}, f)

lines = [
    'tunnel: ' + data['t'],
    'credentials-file: /etc/cloudflared/creds.json',
    '',
    '# All traffic → Caddy. Caddy routes by hostname and handles WebSocket upgrades.',
    'originRequest:',
    '  http2Origin: false',
    '',
    'ingress:',
    '  - service: http://caddy:80',
    '',
]

with open('cloudflared/config.yaml', 'w') as f:
    f.write('\n'.join(lines))

print('Cloudflare Tunnel config generated → caddy:80 (tunnel: ' + data['t'] + ')')
PY
fi

# Generate the DERP map served by Headscale to all clients.
# DERP_HOSTNAME must point (direct DNS, NOT Cloudflare-proxied) to the host
# running the derper with 80/443 TCP and 3478 UDP reachable.
if [ -n "${DERP_HOSTNAME:-}" ]; then
  cat > headscale/derp.yaml <<EOF
# Generated by deploy.sh — do not edit manually.
regions:
  900:
    regionid: 900
    regioncode: umbra
    regionname: "Umbra DERP"
    nodes:
      - name: "900a"
        regionid: 900
        hostname: "${DERP_HOSTNAME}"
        stunport: 3478
        stunonly: false
        derpport: 443
EOF
  echo "DERP map generated for ${DERP_HOSTNAME}"
  # The standalone derper replaces the embedded DERP server.
  export HEADSCALE_DERP_SERVER_ENABLED=false
else
  cat > headscale/derp.yaml <<EOF
# Generated by deploy.sh — no external DERP relay configured.
regions: {}
EOF
  if [ "$TLS_MODE" = "1" ]; then
    echo "DERP: Headscale's embedded relay, served directly over TLS on 443."
  elif [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ] || [[ "${HEADSCALE_EXTERNAL_URL:-}" == https://* ]]; then
    # Headscale is (or is about to be) proxied, and nothing else provides a
    # relay. This is the combination that produces "Relay server unavailable"
    # on every CGNAT client — fail now rather than after a day of debugging.
    echo "ERROR: Headscale is served through a proxy/tunnel with no DERP relay." >&2
    echo "       A proxy cannot carry the embedded DERP channel, so nodes behind" >&2
    echo "       CGNAT will never connect. Pick one:" >&2
    echo "         - set HEADSCALE_TLS_HOSTNAME (Headscale serves TLS itself), or" >&2
    echo "         - set DERP_HOSTNAME (+ DERP_RUN_LOCAL=1 on a public host)." >&2
    echo "       See DEPLOYMENT.md." >&2
    exit 1
  else
    echo "WARNING: no DERP relay configured — LAN-only deployment."
    echo "         Nodes behind CGNAT or UDP-filtered networks will NOT connect."
  fi
fi

# Export Caddy hostname env vars derived from public URLs.
# In TLS mode Headscale is served directly, so Caddy must NOT claim its
# hostname — point that vhost at an inert name instead.
if [ "$TLS_MODE" = "1" ]; then
  export HS_HOST="headscale.disabled.invalid"
else
  export HS_HOST=$(python3 -c "from urllib.parse import urlparse; import os; u=os.environ.get('HEADSCALE_EXTERNAL_URL','http://localhost:8080'); print(urlparse(u).netloc or u.split('/')[0])")
fi
export API_HOST=$(python3 -c "from urllib.parse import urlparse; import os; u=os.environ.get('API_PUBLIC_URL','http://localhost:3333'); print(urlparse(u).netloc or u.split('/')[0])")
export WEB_HOST=$(python3 -c "from urllib.parse import urlparse; import os; u=os.environ.get('WEB_PUBLIC_URL','http://localhost:3000'); print(urlparse(u).netloc or u.split('/')[0])")

echo "Caddy hostnames: web=$WEB_HOST  api=$API_HOST  hs=$HS_HOST"

# Bearer tokens in cleartext over the internet is the quiet way to lose an
# account: a single captured request hands over a session valid for 30 days.
for pair in "API_PUBLIC_URL:${API_PUBLIC_URL:-}" "WEB_PUBLIC_URL:${WEB_PUBLIC_URL:-}"; do
  name="${pair%%:*}"; url="${pair#*:}"
  case "$url" in
    ""|http://localhost*|http://127.0.0.1*) ;;
    http://*)
      echo "WARNING: $name is plain HTTP on a non-local address ($url)."
      echo "         Session tokens will travel in the clear. Put it behind TLS —"
      echo "         a Cloudflare Tunnel works for the API and the dashboard"
      echo "         (never for Headscale). See DEPLOYMENT.md."
      ;;
  esac
done

if [ -z "${DB_PASSWORD:-}" ]; then
  echo "WARNING: DB_PASSWORD is not set — postgres uses the default password."
  echo "         It only listens on 127.0.0.1, but set DB_PASSWORD in .env"
  echo "         BEFORE the first deploy (it is baked in at volume init)."
fi

PROFILES=(--profile prod)
[ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ] && PROFILES+=(--profile tunnel)
# Run the derper here only when THIS host has a public IP (VPS deployment).
if [ "${DERP_RUN_LOCAL:-0}" = "1" ]; then
  if [ -z "${DERP_HOSTNAME:-}" ]; then
    echo "ERROR: DERP_RUN_LOCAL=1 requires DERP_HOSTNAME to be set." >&2
    exit 1
  fi
  PROFILES+=(--profile derp)
fi

docker compose "${COMPOSE_FILES[@]}" "${PROFILES[@]}" up -d --build

# The Caddyfile is a bind mount, so editing it changes nothing on its own:
# compose sees no difference in the service definition and leaves the container
# running with the configuration it started with. The edit appears to have been
# applied — the file on disk is right, the deploy reports success — and the
# tunnel goes on reporting 502 against a Caddy still listening where it used to.
RUNNING="$(docker ps --format '{{.Names}}' || true)"
if [[ "$RUNNING" == *"umbra-caddy"* ]]; then
  if ! docker exec umbra-caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null; then
    echo "WARNING: Caddy refused to reload its configuration — check the Caddyfile."
    echo "         The old one stays in effect until it does."
    echo ""
  fi
fi

echo ""

# A tunnel configured from the Cloudflare dashboard ignores the config.yaml we
# just generated — silently, and with no sign of it anywhere in this repo. The
# hostnames then come from a web UI nobody can diff, and a mismatch surfaces as
# a bare 404 from the catch-all rule, which reads like a broken API and is not
# one. Cloudflare pushes such a config with a version number; the local file
# never has one.
#
# Matched in bash rather than through `| grep -q`: this script runs under
# `set -o pipefail`, and grep -q exits on its first match, which hands the
# upstream `docker logs` a SIGPIPE. The pipeline then reports failure exactly
# when the pattern was found, so the warning could never fire.
if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
  sleep 2
  TUNNEL_LOG="$(docker logs umbra-cloudflared 2>&1 || true)"
  if [[ "$TUNNEL_LOG" == *"Updated to new configuration"* ]]; then
    echo "WARNING: this tunnel is managed from the Cloudflare dashboard, so the"
    echo "         config.yaml generated above is never read. The hostnames in"
    echo "         effect are the ones under Zero Trust > Networks > Tunnels >"
    echo "         Published application routes, and they can disagree with the"
    echo "         ones printed here without anything saying so — a mismatch"
    echo "         comes back as a bare 404 from the catch-all rule."
    echo ""
    echo "         Point those routes at http://caddy:80 so the Caddyfile in this"
    echo "         repo is what actually routes. Emptying the list does NOT hand"
    echo "         control back: a dashboard-created tunnel stays that way, and"
    echo "         with no routes left the catch-all 404s everything. Only a"
    echo "         tunnel created with 'cloudflared tunnel create' reads"
    echo "         config.yaml."
    echo ""
  fi
fi

echo "Umbra deployed."
if [ "$TLS_MODE" = "1" ]; then
  echo "Headscale certificate is issued lazily, on the first TLS handshake."
  echo "Check it with:  curl -sSI ${HEADSCALE_EXTERNAL_URL}/health"
fi
