#!/usr/bin/env bash
set -euo pipefail

# Load .env
if [ -f .env ]; then
  set -a; source .env; set +a
fi

# Generate cloudflared local config from CLOUDFLARE_TUNNEL_TOKEN
# Cloudflare Tunnel → Caddy (HTTP/1.1) → services
# Caddy handles WebSocket Upgrade natively (required for Headscale TS2021)
if [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then
  mkdir -p cloudflared
  python3 - <<'PY'
import base64, json, os
from urllib.parse import urlparse

def host(url):
    p = urlparse(url)
    return p.netloc if p.netloc else url

token = os.environ['CLOUDFLARE_TUNNEL_TOKEN']
padding = (4 - len(token) % 4) % 4
data = json.loads(base64.b64decode(token + '=' * padding).decode())

with open('cloudflared/creds.json', 'w') as f:
    json.dump({'AccountTag': data['a'], 'TunnelID': data['t'], 'TunnelSecret': data['s']}, f)

lines = [
    'tunnel: ' + data['t'],
    'credentials-file: /etc/cloudflared/creds.json',
    '',
    '# All traffic → Caddy. Caddy routes by hostname and handles WebSocket upgrades.',
    'originRequest:',
    '  http2Origin: false',
    '',
    'ingress:',
    '  - service: http://caddy:80',
    '',
]

with open('cloudflared/config.yaml', 'w') as f:
    f.write('\n'.join(lines))

print('Cloudflare Tunnel config generated → caddy:80 (tunnel: ' + data['t'] + ')')
PY
fi

# Generate the DERP map served by Headscale to all clients.
# DERP_HOSTNAME must point (direct DNS, NOT Cloudflare-proxied) to the host
# running the derper with 80/443 TCP and 3478 UDP reachable.
if [ -n "${DERP_HOSTNAME:-}" ]; then
  cat > headscale/derp.yaml <<EOF
# Generated by deploy.sh — do not edit manually.
regions:
  900:
    regionid: 900
    regioncode: umbra
    regionname: "Umbra DERP"
    nodes:
      - name: "900a"
        regionid: 900
        hostname: "${DERP_HOSTNAME}"
        stunport: 3478
        stunonly: false
        derpport: 443
EOF
  echo "DERP map generated for ${DERP_HOSTNAME}"
  # The standalone derper replaces the embedded DERP server.
  export HEADSCALE_DERP_SERVER_ENABLED=false
else
  cat > headscale/derp.yaml <<EOF
# Generated by deploy.sh — no DERP relay configured.
regions: {}
EOF
  echo "WARNING: DERP_HOSTNAME is not set — no DERP relay in the mesh."
  echo "         Nodes behind CGNAT or UDP-filtered networks will NOT connect."
  echo "         Set DERP_HOSTNAME (+ DERP_RUN_LOCAL=1 if this host is public)."
fi

# Export Caddy hostname env vars derived from public URLs
export HS_HOST=$(python3 -c "from urllib.parse import urlparse; import os; u=os.environ.get('HEADSCALE_EXTERNAL_URL','http://localhost:8080'); print(urlparse(u).netloc or u.split('/')[0])")
export API_HOST=$(python3 -c "from urllib.parse import urlparse; import os; u=os.environ.get('API_PUBLIC_URL','http://localhost:3333'); print(urlparse(u).netloc or u.split('/')[0])")
export WEB_HOST=$(python3 -c "from urllib.parse import urlparse; import os; u=os.environ.get('WEB_PUBLIC_URL','http://localhost:3000'); print(urlparse(u).netloc or u.split('/')[0])")

echo "Caddy hostnames: web=$WEB_HOST  api=$API_HOST  hs=$HS_HOST"

if [ -z "${DB_PASSWORD:-}" ]; then
  echo "WARNING: DB_PASSWORD is not set — postgres uses the default password."
  echo "         It only listens on 127.0.0.1, but set DB_PASSWORD in .env"
  echo "         BEFORE the first deploy (it is baked in at volume init)."
fi

PROFILES=(--profile prod)
[ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ] && PROFILES+=(--profile tunnel)
# Run the derper here only when THIS host has a public IP (VPS deployment).
if [ "${DERP_RUN_LOCAL:-0}" = "1" ]; then
  if [ -z "${DERP_HOSTNAME:-}" ]; then
    echo "ERROR: DERP_RUN_LOCAL=1 requires DERP_HOSTNAME to be set." >&2
    exit 1
  fi
  PROFILES+=(--profile derp)
fi

docker compose "${PROFILES[@]}" up -d --build
echo ""
echo "Umbra deployed."
