export type Lang = 'fr' | 'en'

const TR: Record<Lang, Record<string, string>> = {
  fr: {
    // Auth
    auth_tagline_login_1: 'Vos noeuds VPN,',
    auth_tagline_login_2: 'sous votre contrôle.',
    auth_desc_login: 'Déploiement en une commande. Interface unifiée. Aucune dépendance à un service tiers.',
    auth_tagline_register_1: 'Prêt en',
    auth_tagline_register_2: 'une commande.',
    auth_desc_register: 'Créez votre compte, ajoutez un noeud, connectez-vous. Tout en moins de 5 minutes.',
    auth_login_title: 'Connexion à votre espace',
    auth_register_title: 'Créer un compte gratuit',
    auth_oauth_notice: 'OAuth disponible après la sortie du backend.',
    auth_oauth_github: 'Continuer avec GitHub',
    auth_oauth_google: 'Continuer avec Google',
    auth_or_email: 'ou par email',
    auth_email: 'Email',
    auth_email_ph: 'ex: vous@example.com',
    auth_password: 'Mot de passe',
    auth_password_confirm: 'Confirmer le mot de passe',
    auth_password_forgot: 'Mot de passe oublié ?',
    auth_password_mismatch: 'Les mots de passe ne correspondent pas',
    auth_username: "Nom d'utilisateur",
    auth_username_ph: 'ex: John Doe',
    auth_login_btn: 'Connexion →',
    auth_register_btn: 'Créer le compte →',
    auth_no_account: 'Pas encore de compte ?',
    auth_register_link: 'Inscription gratuite',
    auth_have_account: 'Déjà un compte ?',
    auth_login_link: 'Se connecter',
    auth_strength_0: '',
    auth_strength_1: 'Faible',
    auth_strength_2: 'Moyen',
    auth_strength_3: 'Fort',
    auth_strength_4: 'Très fort',
    auth_err_fill: 'Remplis tous les champs.',
    auth_err_invalid: 'Identifiants invalides.',
    auth_err_register: 'Impossible de créer le compte.',
    auth_err_forgot_email: 'Entre ton email pour recevoir le lien de réinitialisation.',
    auth_forgot_sent: 'Lien de réinitialisation envoyé à',

    // Sidebar
    side_sub: 'VPN Manager',
    side_nav: 'Navigation',
    side_account: 'Compte',
    side_dashboard: 'Dashboard',
    side_nodes: 'Noeuds',
    side_connections: 'Connexions',
    side_alerts: 'Alertes',
    side_api_keys: 'Clés API',
    side_settings: 'Paramètres',
    side_account_label: 'Compte',
    side_logout: 'Déconnexion',

    // Common
    common_back:      'Retour',
    common_cancel:    'Annuler',
    common_save:      'Enregistrer',
    common_close:     'Fermer',
    common_delete:    'Supprimer',
    common_edit:      'Modifier',
    common_manage:    'Gérer',
    common_loading:   'Chargement…',
    common_saving:    '…',
    common_soon:      'Bientôt',
    common_dash:      '—',
    common_just_now:  "à l'instant",
    common_min_ago:   'il y a {n}min',
    common_hour_ago:  'il y a {n}h',
    common_day_ago:   'il y a {n}j',
    common_label_session: 'Session',
    common_label_register: 'Inscription',

    // Settings — page
    settings_title: 'Paramètres',
    settings_sub:   'Préférences et configuration du compte',

    // Settings — nav
    settings_nav_appearance:    'Apparence',
    settings_nav_account:       'Compte',
    settings_nav_notifications: 'Notifications',
    settings_nav_security:      'Sécurité',
    settings_nav_team:          'Équipe',
    settings_nav_agent:         'Agent & réseau',
    settings_nav_danger:        'Zone de danger',

    // Settings — appearance
    settings_appearance_title:  'Apparence',
    settings_theme_label:       'Thème',
    settings_theme_sub:         "Couleurs de l'interface",
    settings_theme_dark:        'Dark',
    settings_theme_light:       'Light',
    settings_lang_label:        'Langue',
    settings_lang_sub:          "Langue de l'interface",

    // Settings — account
    settings_account_title:     'Compte',
    settings_plan_free:         'Free',
    settings_account_name:      'Nom',
    settings_account_email:     'Email',
    settings_account_password:  'Mot de passe',
    settings_account_password_sub: 'Modifier votre mot de passe',
    settings_account_plan:      'Plan',
    settings_account_plan_sub:  'Free — 5 noeuds · 1 utilisateur · historique 24h',
    settings_account_view_plans: 'Voir les plans →',

    // Settings — notifications
    settings_notif_title:    'Notifications',
    settings_notif_crit_label: 'Alertes critiques',
    settings_notif_crit_sub:   'Email immédiat pour chaque alerte critique',
    settings_notif_warn_label: 'Alertes warning',
    settings_notif_warn_sub:   'Email pour les avertissements système',
    settings_notif_offline_label: 'Noeud hors ligne',
    settings_notif_offline_sub:   'Notification si un noeud devient injoignable',
    settings_notif_weekly_label:  'Résumé hebdomadaire',
    settings_notif_weekly_sub:    'Rapport récapitulatif chaque lundi matin',
    settings_notif_update_label:  'Mises à jour disponibles',
    settings_notif_update_sub:    "Notification lors de nouvelles versions de l'agent",

    // Settings — security
    settings_security_title:  'Sécurité',
    settings_2fa_label:       'Authentification 2FA',
    settings_2fa_sub:         'TOTP via application (Aegis, Bitwarden…)',
    settings_sessions_label:  'Sessions actives',
    settings_sessions_sub:    'Gérer vos sessions ouvertes',
    settings_logs_label:      'Logs de connexion',
    settings_logs_sub:        'Historique des accès au compte',

    // Settings — team
    common_create: 'Créer',
    settings_danger_nodes_sub_owned: "Révoque les agents de vos noeuds personnels. Les noeuds d'organisation et ceux qu'on vous a partagés ne sont pas concernés.",
    addnode_owner: 'Propriétaire',
    nd_action_transfer: 'Changer de propriétaire',
    nd_perm_read: 'Lecture seule',
    nd_share_add: 'Partager',
    inst_nav: 'Instance',
    inst_users_one: '{n} compte',
    inst_users_many: '{n} comptes',
    inst_orgs_empty: 'Aucune organisation',
    inst_edit_user: 'Modifier ce compte',
    inst_reset_pwd: 'Réinitialiser le mot de passe',
    inst_add_member: 'Ajouter un membre',
    inst_add_member_ph: 'Adresse email du compte',
    inst_add: 'Ajouter',
    notif_member_added: 'Membre ajouté',
    confirm_remove_member_title: 'Retirer ce membre',
    confirm_remove_member: "Retirer {name} de l'organisation ? Il perdra l'accès à ses noeuds.",
    confirm_leave_org_title: "Quitter l'organisation",
    confirm_leave_org: 'Quitter « {name} » ? Vous perdrez l\'accès à ses noeuds.',
    confirm_leave_org_btn: 'Quitter',
    inst_reset_hint: "Transmettez ce mot de passe à {email}. Ses sessions ont été fermées et il devra le changer à la connexion.",
    org_role_owner: 'Propriétaire',
    confirm_dissolve_org: "Dissoudre « {name} » ? Ses membres perdront l'accès partagé. Action irréversible.",
    confirm_suspend_user: 'Suspendre {email} ? La personne ne pourra plus se connecter.',
    confirm_reset_pwd: 'Réinitialiser le mot de passe de {email} ? Ses sessions en cours seront fermées.',
    inst_edit_org: "Renommer l'organisation",
    inst_edit_org_hint: "Le nom est ce que voient ses membres. Dépliez l'équipe pour gérer sa composition.",
    inst_orgs_one: '{n} organisation',
    inst_orgs_many: '{n} organisations',
    inst_org_delete: 'Dissoudre cette organisation',
    notif_org_deleted: 'Organisation dissoute',
    inst_title: 'Instance',
    inst_operator: 'opérateur',
    inst_stats_label: 'Comptes · organisations · noeuds',
    inst_stats_sub: 'Ce qui tourne sur ce serveur',
    inst_reg_label: 'Inscriptions',
    inst_reg_sub: 'Qui peut créer un compte sur cette instance',
    inst_mode_open: 'Ouvertes',
    inst_mode_invite: 'Sur invitation',
    inst_mode_closed: 'Fermées',
    inst_create_label: 'Créer un compte',
    inst_create_sub: 'Avec un mot de passe temporaire à changer à la première connexion',
    inst_create: 'Créer',
    inst_create_title: 'Nouveau compte',
    inst_create_hint: "Le mot de passe temporaire ne s'affichera qu'une seule fois.",
    inst_create_name: 'Nom (optionnel)',
    inst_create_name_ph: 'Prénom Nom',
    inst_temp_hint: 'Transmettez ce mot de passe à {email}. Il devra le changer à la connexion.',
    inst_active: 'actif',
    inst_suspended: 'suspendu',
    inst_suspend: 'Suspendre ce compte',
    inst_restore: 'Réactiver ce compte',
    inst_pending_pwd: 'mdp temporaire',
    inst_nodes_one: '{n} noeud',
    inst_nodes_many: '{n} noeuds',
    notif_inst_saved: 'Réglage enregistré',
    notif_inst_failed: 'Modification impossible',
    force_pwd_title: 'Choisissez un mot de passe',
    force_pwd_sub: 'Votre compte a été créé avec un mot de passe temporaire. Remplacez-le pour continuer.',
    force_pwd_current: 'Mot de passe temporaire',
    force_pwd_new: 'Nouveau mot de passe',
    force_pwd_confirm: 'Confirmation',
    force_pwd_short: '8 caractères minimum',
    force_pwd_mismatch: 'Les mots de passe ne correspondent pas',
    force_pwd_submit: 'Enregistrer',
    force_pwd_saving: 'Enregistrement…',
    force_pwd_error: 'Impossible de modifier le mot de passe',
    nd_share_org_target: 'Organisation entière',
    nd_share_email_hint: "Saisissez l'adresse email d'un compte UMBRA existant.",
    notif_share_done: 'Accès accordé',
    notif_share_failed: 'Partage impossible',
    nd_perm_connect: 'Connexion',
    nd_perm_manage: 'Gestion',
    nd_transfer_title: 'Changer de propriétaire',
    nd_transfer_sub: "Le noeud rejoint le réseau du nouveau propriétaire. Le céder à une personne vous en retire la propriété.",
    nd_transfer_confirm: 'Transférer',
    notif_transfer_done: 'Propriétaire modifié',
    notif_transfer_failed: 'Transfert impossible',
    addnode_owner_personal: 'Personnel',
    addnode_owner_hint: "Un noeud d'organisation est accessible à tous ses membres.",
    node_org_badge: 'Org',
    org_you: 'vous',
    org_pending: 'En attente',
    org_role_admin: 'Admin',
    org_role_member: 'Membre',
    settings_team_create_label: 'Créer une organisation',
    settings_team_create_sub: "Partagez vos noeuds avec une équipe, avec des rôles distincts.",
    settings_team_create: 'Créer',
    settings_team_join_label: 'Rejoindre une organisation',
    settings_team_join_sub: "Collez le code d'invitation qu'on vous a transmis.",
    settings_team_join_ph: 'umbra_invite_…',
    settings_team_join: 'Rejoindre',
    settings_team_invite: 'Inviter',
    settings_team_invite_admin_only: 'Réservé aux admins',
    settings_team_plan_label: 'Membres',
    settings_team_plan_sub: "Personnes ayant accès aux noeuds de l'organisation",
    settings_team_members_one: '{n} membre',
    settings_team_members_many: '{n} membres',
    modal_create_org_title: 'Nouvelle organisation',
    modal_create_org_name: 'Nom',
    modal_create_org_ph: 'Mon équipe',
    modal_create_org_hint: "Vous en serez propriétaire. Les noeuds de l'organisation forment un réseau isolé du vôtre.",
    modal_invite_title: 'Inviter un membre',
    modal_invite_email: 'Adresse email',
    modal_invite_role: 'Rôle',
    modal_invite_send: "Générer l'invitation",
    modal_invite_token_hint: "Transmettez ce code à {email}. Il n'est affiché qu'une fois et expire dans 7 jours.",
    notif_org_created: 'Organisation créée',
    notif_org_create_failed: "Impossible de créer l'organisation",
    notif_org_joined: 'Organisation rejointe',
    notif_org_join_failed: 'Invitation invalide ou expirée',
    notif_invite_failed: "Impossible d'envoyer l'invitation",
    notif_role_failed: 'Impossible de modifier le rôle',
    notif_remove_failed: 'Impossible de retirer ce membre',
    settings_team_title:      'Équipe',
    settings_team_invite_label: 'Inviter un membre',
    settings_team_invite_sub:   "Accès partagé aux noeuds de l'organisation",

    // Settings — agent
    settings_agent_title:     'Agent & réseau',
    settings_heartbeat_label: 'Intervalle heartbeat',
    settings_heartbeat_sub:   'Fréquence de rapport des agents',
    settings_autoupdate_label: 'Auto-update des agents',
    settings_autoupdate_sub:   'Mise à jour automatique vers la dernière version stable',
    settings_subnet_label:    'Subnet VPN par défaut',
    settings_subnet_sub:      "Plage d'adresses IP du réseau UMBRA",
    settings_hb_1min:         '1min',
    settings_hb_5min:         '5min',

    // Settings — danger
    settings_danger_title:        'Zone de danger',
    settings_danger_nodes_label:  'Supprimer tous les noeuds',
    settings_danger_nodes_sub:    'Révoque tous les agents et supprime les données associées',
    settings_danger_account_label: 'Supprimer le compte',
    settings_danger_account_sub:   'Action irréversible — toutes les données seront perdues',

    // Modals — edit name
    modal_edit_name_title:   'Modifier le nom',
    modal_edit_name_label:   'Nom affiché',
    modal_edit_name_ph:      'ex: alec',
    modal_edit_name_err:     'Impossible de mettre à jour le nom.',
    notif_name_updated:      'Nom mis à jour',

    // Modals — edit password
    modal_edit_pwd_title:    'Modifier le mot de passe',
    modal_edit_pwd_old:      'Mot de passe actuel',
    modal_edit_pwd_new:      'Nouveau mot de passe',
    modal_edit_pwd_confirm:  'Confirmer',
    modal_edit_pwd_err:      'Impossible de modifier le mot de passe.',
    notif_pwd_updated:       'Mot de passe modifié',
    notif_pwd_updated_desc:  'Vos sessions existantes restent actives.',

    // Modals — upgrade
    modal_upgrade_title:     'Plans & tarifs',
    modal_upgrade_sub:       'Choisissez le plan adapté à vos besoins',
    plan_current:            'Plan actuel',
    plan_free_name:          'Free',
    plan_free_price:         'Gratuit',
    plan_free_period:        'pour toujours',
    plan_free_f1:            '5 noeuds',
    plan_free_f2:            '1 utilisateur',
    plan_free_f3:            'Historique 24h',
    plan_free_f4:            '2 clés API',
    plan_free_f5:            'Dashboard web',
    plan_free_f6:            'Support communauté',
    plan_pro_label:          'Recommandé',
    plan_pro_name:           'Pro',
    plan_pro_price:          '8,90 €',
    plan_pro_per:            '/mois',
    plan_pro_period:         'facturé mensuellement',
    plan_pro_f1:             '25 noeuds',
    plan_pro_f2:             '10 utilisateurs',
    plan_pro_f3:             'Historique 90 jours',
    plan_pro_f4:             'Clés API illimitées',
    plan_pro_f5:             'Alertes email + webhook',
    plan_pro_f6:             'Support prioritaire 48h',
    plan_pro_cta:            'Passer à Pro →',
    plan_lifetime_label:     'Paiement unique',
    plan_lifetime_name:      'Lifetime',
    plan_lifetime_price:     '149 €',
    plan_lifetime_period:    'une seule fois, à vie',
    plan_lifetime_cta:       'Obtenir Lifetime →',
    plan_biz_label:          'Entreprises',
    plan_biz_name:           'Business',
    plan_biz_sub:            'Tarif adapté à votre organisation — sur devis.',
    plan_biz_f1:             'Noeuds illimités',
    plan_biz_f2:             'Utilisateurs illimités',
    plan_biz_f3:             'Historique 1 an',
    plan_biz_f4:             'SSO (SAML / OIDC)',
    plan_biz_f5:             "Logs d'audit",
    plan_biz_price:          'Sur devis',
    plan_biz_period:         'tarif personnalisé',
    plan_biz_cta:            'Prendre contact →',

    // Modals — sessions
    modal_sessions_title:    'Sessions actives',
    sessions_count_one:      '{n} session',
    sessions_count_many:     '{n} sessions',
    sessions_load_err:       'Impossible de charger les sessions.',
    sessions_current_badge:  'Actuelle',
    sessions_created:        'Créée {time}',
    sessions_last_used:      'Dernière activité {time}',
    sessions_revoke:         'Révoquer',
    sessions_revoke_others:  'Révoquer toutes les autres',
    sessions_empty:          'Aucune session active',
    notif_session_revoked:   'Session révoquée',
    notif_session_revoke_err: 'Révocation échouée',
    notif_sessions_revoked_one: '{n} session révoquée',
    notif_sessions_revoked_many: '{n} sessions révoquées',
    notif_sessions_revoked_desc: 'Seule votre session actuelle reste active.',

    // Modals — delete nodes
    modal_delete_nodes_title: 'Supprimer tous les noeuds ?',
    modal_delete_nodes_warn:  'Tous les agents seront révoqués et les données associées supprimées. Cette action est irréversible.',
    modal_delete_nodes_btn_one:  'Supprimer {n} noeud',
    modal_delete_nodes_btn_many: 'Supprimer {n} noeuds',
    modal_delete_nodes_progress: 'Suppression…',
    notif_nodes_deleted_one:  '{n} noeud supprimé',
    notif_nodes_deleted_many: '{n} noeuds supprimés',
    notif_nodes_deleted_desc: 'Tous les agents associés ont été révoqués.',
    notif_delete_failed:      'Suppression échouée',

    // Modals — delete account
    modal_delete_account_title: 'Supprimer le compte',
    modal_delete_account_warn:  'Toutes vos données seront définitivement supprimées. Cette action est irréversible.',
    modal_delete_account_label_pre: 'Tapez',
    modal_delete_account_label_post: 'pour confirmer',
    modal_delete_account_word: 'supprimer',
    modal_delete_account_btn:  'Supprimer définitivement',
    notif_soon_title:          'Bientôt disponible',
    notif_account_delete_soon_desc: "La suppression de compte n'est pas encore exposée par l'API.",
    notif_account_deleted:          'Compte supprimé',

    // Login logs
    modal_login_logs_title:    'Logs de connexion',
    login_log_action_login:    'Connexion',
    login_log_action_logout:   'Déconnexion',
    login_logs_empty:          'Aucun historique',
    sessions_on:               'sur',

    // Dashboard
    dash_title:           'Dashboard',
    dash_new_node:        '+ Nouveau noeud',
    dash_stat_active:     'Noeuds actifs',
    dash_stat_active_sub: '{off} hors ligne · {warn} alerte',
    dash_stat_devices:    'Appareils',
    dash_stat_devices_sub: 'enregistrés',
    dash_stat_bandwidth:  'Bande passante',
    dash_stat_bandwidth_sub: "aujourd'hui",
    dash_stat_latency:    'Latence moy.',
    dash_stat_latency_sub: 'sur les noeuds actifs',
    dash_map_title:       'Carte des noeuds',
    dash_map_hint:        'Clic pour se connecter',
    dash_section_nodes:   'Noeuds',
    dash_view_all:        'Voir tout ({n}) →',
    dash_empty:           'Aucun noeud',

    // Node table headers
    node_th_node:         'Noeud',
    node_th_location:     'Localisation',
    node_th_status:       'Statut',
    node_th_latency:      'Latence',
    node_th_cpu:          'CPU',

    // Map tooltip
    mtt_location:         'Localisation',
    mtt_latency:          'Latence',
    mtt_cpu:              'CPU',
    mtt_disconnect:       'Cliquer pour déconnecter',
    mtt_offline:          'Noeud hors ligne',
    mtt_pending:          'Connexion en attente…',
    mtt_connect:          'Cliquer pour se connecter',
    mtt_cluster_count:    '{n} noeuds',
    mtt_view_all:         'Voir tous les noeuds →',

    // Date locale (used by toLocaleDateString)
    date_locale:          'fr-FR',

    // Status labels
    status_online:    'En ligne',
    status_offline:   'Hors ligne',
    status_warning:   'Alerte',
    status_pending:   'En attente',
    status_connected: 'Connecté',

    // Nodes list page
    nodes_title:        'Noeuds',
    nodes_sub_one:      '{n} noeud enregistré',
    nodes_sub_many:     '{n} noeuds enregistrés',
    nodes_filter_all:   'Tous',
    nodes_filter_all_f: 'Toutes',
    nodes_filter_online:    'En ligne',
    nodes_filter_connected: 'Connecté',
    nodes_filter_warning:   'Alerte',
    nodes_filter_offline:   'Hors ligne',
    nodes_cat_sbc:     'SBC',
    nodes_cat_vps:     'VPS',
    nodes_cat_router:  'Router',
    nodes_cat_nas:     'NAS',
    nodes_cat_desktop: 'Desktop',
    nodes_cat_other:   'Autre',
    nodes_empty:       'Aucun noeud trouvé',

    // Node detail
    nd_back:           '← Retour',
    nd_loading:        'Chargement…',
    nd_not_found:      'Noeud introuvable',
    nd_card_system:    'Système',
    nd_card_machine:   'Machine',
    nd_card_wireguard: 'Réseau VPN',
    nd_card_agent:     'Agent UMBRA',
    nd_card_actions:   'Actions',
    nd_metric_cpu:     'CPU',
    nd_metric_ram:     'RAM',
    nd_metric_disk:    'Disque',
    nd_metric_temp:    'Température',
    nd_metric_latency: 'Latence',
    nd_metric_uptime:  'Uptime',
    nd_period_1h:      '1h',
    nd_period_1d:      '1j',
    nd_period_1w:      '1s',
    nd_period_1m:      '1m',
    nd_period_1y:      '1a',
    nd_chart_bandwidth: 'Bande passante',
    nd_chart_latency:   'Latence',
    nd_chart_load:      'Charge système',
    nd_act_restart:    "Redémarrer l'agent",
    nd_act_regen:      'Régénérer les clés',
    nd_act_download:   'Télécharger .conf',
    nd_act_logs:       'Voir les logs',
    nd_act_delete:     'Supprimer le noeud',
    nd_machine_model:  'Modèle',
    nd_machine_ram:    'RAM',
    nd_machine_os:     'OS',
    nd_machine_arch:   'Architecture',
    nd_machine_pubip:  'IP publique',
    nd_machine_loc:    'Localisation',
    nd_machine_isp:    'FAI',
    nd_wg_iface:       'Interface',
    nd_wg_vpnip:       'IP VPN',
    nd_wg_port:        'Port',
    nd_wg_pubkey:      'Clé publique',
    nd_wg_peers:       'Pairs',
    nd_wg_configure:   'Configurer',
    nd_wg_manage:      'Gérer',
    nd_agent_version:  'Version',
    nd_agent_heartbeat: 'Dernier heartbeat',
    nd_agent_interval: 'Intervalle',
    nd_agent_autoupdate: 'Auto-update',
    nd_agent_jwt:      'JWT expire',
    nd_agent_update_avail: 'Mise à jour disponible',
    nd_agent_update_btn: 'Mettre à jour',
    nd_delete_title:   'Supprimer ce noeud ?',
    nd_delete_warn:    "L'agent sera révoqué et toutes les données associées seront supprimées. Cette action est irréversible.",
    nd_delete_progress: 'Suppression…',
    nd_logs_title:     'Logs récents',
    nd_logs_empty:     'Aucune entrée',
    nd_wg_save:        'Enregistrer',
    nd_peer_pubkey:    'Clé publique',
    nd_peer_allowed:   'AllowedIPs',
    nd_peer_endpoint:  'Endpoint',
    nd_peer_remove:    'Retirer',
    notif_restart_done: 'Agent redémarré',
    notif_regen_done:   'Clés régénérées',
    notif_regen_desc:   'Le noeud doit être reconnecté avec la nouvelle configuration.',
    notif_download_done: 'Configuration téléchargée',
    notif_node_deleted: 'Noeud supprimé',
    notif_pubkey_copied: 'Clé publique copiée',
    notif_peer_added:   'Pair ajouté',
    notif_peer_removed: 'Pair retiré',
    nd_subtitle_sep:   ' · ',

    // Node row
    row_cut:        'Couper',
    row_connect:    'Connecter',
    row_warn_cpu:   'CPU',

    // VPN bar
    vpn_latency:    'Latence',
    vpn_upload:     'Upload',
    vpn_download:   'Download',
    vpn_disconnect: 'Déconnecter',

    // Connect modal
    conn_modal_title:       'Se connecter via',
    conn_modal_sub:         'Exécute l\'une de ces commandes sur la machine à connecter.',
    conn_modal_new:         'Première connexion',
    conn_modal_new_hint:    '— jamais rejoint ce réseau Headscale',
    conn_modal_switch:      'Déjà sur ce réseau',
    conn_modal_switch_hint: '— machine déjà connectée à Headscale',
    conn_modal_copy:        'Copier',
    conn_modal_copied:      'Copié !',
    conn_modal_no_headscale:'Headscale non configuré sur ce serveur.',
    conn_modal_note:        'La connexion s\'active dès que la commande est exécutée. sudo peut être requis sur certains systèmes.',
    conn_modal_web_notice:  'Application web — exécutez la commande dans un terminal sur cette machine. L\'application desktop automatisera cette étape.',
    conn_disconnect_toast_title: 'VPN déconnecté — pour désactiver le tunnel :',

    // Node detail (extras)
    nd_back_link:        '← Mes noeuds',
    nd_share:            'Partager',
    nd_connect:          'Se connecter',
    nd_disconnect:       'Déconnecter',
    nd_metrics_title:    'Métriques système',
    nd_heartbeat_ago:    'heartbeat il y a 2s',
    nd_period_1h_label:  'dernière heure',
    nd_period_1d_label:  'dernières 24h',
    nd_period_1w_label:  'dernière semaine',
    nd_period_1m_label:  'dernier mois',
    nd_period_1y_label:  'dernière année',
    nd_metric_memory:    'Mémoire',
    nd_metric_disk_label:'Disque',
    nd_metric_temp_label:'Température',
    nd_metric_latency_vpn: 'Latence VPN',
    nd_metric_load_avg:  'load avg 0.18 · 4 cœurs',
    nd_metric_temp_thresh:'seuil critique : 85°C',
    nd_metric_ping:      'ping backend : 14ms',
    nd_metric_uptime_since: 'depuis le {date}',
    nd_history_label:    'Historique —',
    nd_chart_cpu_ram_temp: 'CPU · Mémoire · Température',
    nd_chart_peers:      'Pairs connectés simultanément',
    nd_chart_peers_cat:  'Pairs',
    nd_chart_peers_unit: '{n} pairs',
    nd_action_update_to: 'Mettre à jour vers v{v}',
    nd_action_restarting: 'Redémarrage…',
    nd_action_restart:   "Redémarrer l'agent",
    nd_action_view_logs: 'Voir les logs',
    nd_action_enroll:    'Migrer le noeud',
    nd_action_delete:    'Supprimer le noeud',
    nd_enroll_title:     'Migrer vers une nouvelle machine',
    nd_enroll_desc:      'La machine a lâché ou tu changes de hardware ? Ce token permet de ré-installer l\'agent sur une nouvelle machine. Le noeud conserve son IP VPN, son historique et sa configuration.',
    nd_enroll_step1:     '1. Arrête l\'agent actuel (si accessible)',
    nd_enroll_step1_cmd: 'sudo umbra-agent stop',
    nd_enroll_step2:     '2. Sur la nouvelle machine, lance cette commande :',
    nd_enroll_token_lbl: 'Token brut (si installation manuelle)',
    nd_enroll_copied:    'Copié !',
    nd_enroll_warn:      'Token valable 1 heure · Utilisation unique',
    nd_machine_title:    'Machine',
    nd_info_hardware:    'Hardware',
    nd_info_arch:        'Arch.',
    nd_info_pubip:       'IP publique',
    nd_info_loc:         'Localisation',
    nd_info_isp:         'ISP',
    nd_info_hardware_tip: 'Modèle matériel du périphérique tel que rapporté par l\'agent.',
    nd_info_arch_tip:    'Architecture du processeur (ex: arm64, x86_64).',
    nd_info_os_tip:      'Version du système d\'exploitation installé sur la machine.',
    nd_info_pubip_tip:   'Adresse IP publique de la machine vue depuis Internet.',
    nd_info_loc_tip:     'Géolocalisation approximative basée sur l\'IP publique.',
    nd_info_isp_tip:     'Fournisseur d\'Accès à Internet (FAI) — opérateur réseau de cette machine.',
    nd_wg_iface_badge:   'interface tailscale0',
    nd_wg_vpnip_label:   'IP VPN',
    nd_wg_pubkey_label:  'Clé publique',
    nd_wg_pubkey_copied: 'Copié !',
    nd_wg_pubkey_copy:   'Copier',
    nd_wg_peers_short:   '{n} pair(s) actif(s)',
    nd_agent_title:      'Agent UMBRA',
    nd_version_label:    'Version',
    nd_version_uptodate: 'à jour',
    nd_version_avail:    'v{v} disponible',
    nd_agent_heartbeat_label: 'Dernier heartbeat',
    nd_agent_heartbeat_val:   'il y a 2s',
    nd_agent_interval_label:  'Intervalle',
    nd_agent_autoupdate_label:'Auto-update',
    nd_agent_active:     'Actif',
    nd_agent_inactive:   'Inactif',
    nd_agent_jwt_label:  'JWT expire',
    nd_agent_jwt_val:    'dans 82j',
    nd_actions_title:    'Actions',
    nd_share_title:      'Partager — {name}',
    nd_share_sub:        'Gérer les accès à ce noeud',
    nd_share_add_user:   'Ajouter un utilisateur',
    nd_share_search_ph:  'Nom ou email...',
    nd_share_invite:     'Inviter {q}',
    nd_share_invite_sub: "Envoi d'un email d'invitation",
    nd_share_badge_umbra:'UMBRA',
    nd_share_badge_new:  'Nouveau',
    nd_share_default_perm:'Permission par défaut',
    nd_share_perm_read:  'Lecture',
    nd_share_perm_read_d:'Voir les métriques',
    nd_share_perm_conn:  'Connexion',
    nd_share_perm_conn_d:'Se connecter',
    nd_share_perm_mgmt:  'Gestion',
    nd_share_perm_mgmt_d:'Modifier les réglages',
    nd_share_perm_admin: 'Admin',
    nd_share_perm_admin_d:'Partager et révoquer',
    nd_share_active:     'Accès actifs ({n})',
    nd_share_pending:    'En attente ({n})',
    nd_share_pending_lbl:'Invitation envoyée · {p}',
    nd_share_empty:      'Aucun accès partagé pour ce noeud',
    nd_peer_active:      'Actif',
    nd_peer_inactive:    'Inactif',
    nd_logs_modal_title: 'Logs — {name}',
    nd_logs_modal_sub:   'Activité et événements récents',
    nd_delete_modal_title:'Supprimer {name} ?',
    nd_delete_modal_warn:'Le noeud sera révoqué et toutes ses données supprimées. Cette action est irréversible.',
    nd_delete_modal_btn: 'Supprimer définitivement',
    nd_delete_notif_fail:'Suppression échouée',
    nd_state_loading:    'Chargement...',
    nd_state_not_found:  'Noeud introuvable',
    nd_restart_ok:       'Agent redémarré avec succès',
    nd_restart_warn:     'Agent redémarré — connexion peut être instable momentanément',
    nd_update_started:   'Mise à jour vers v{v} lancée…',
    nd_subtitle:         '{ip}{hw}{os}{ver}',

    // Node detail — peers card
    nd_peers_card_title:  'Pairs du réseau mesh',
    nd_peers_count:       '{active} / {total} connectés',
    nd_peers_th_peer:     'Pair',
    nd_peers_th_pubkey:   'Clé publique',
    nd_peers_th_vpnip:    'IP VPN',
    nd_peers_th_latency:  'Latence',
    nd_peers_th_traffic:  'Trafic ↑↓',
    nd_peers_th_handshake:'Handshake',
    nd_peers_th_status:   'Statut',
    nd_peer_hs_4s:        'il y a 4s',
    nd_peer_hs_2h:        'il y a 2h',
    nd_peer_hs_28s:       'il y a 28s',
    nd_peer_hs_1min:      'il y a 1min',
    nd_peer_hs_Xs:        'il y a {n}s',
    nd_peer_hs_Xm:        'il y a {n}min',
    nd_peer_hs_Xh:        'il y a {n}h',

    // Node detail — activity card
    nd_activity_title:    'Activité récente',
    nd_activity_collapse: 'Réduire ↑',
    nd_activity_view_all: 'Tout voir →',
    nd_act_e1_main:       "alecptt s'est connecté depuis MacBook Pro",
    nd_act_e1_sub:        '100.64.0.10 · IP source 82.120.44.16 · WireGuard',
    nd_act_e1_time:       '14:28:04',
    nd_act_e2_main:       "marie s'est déconnectée",
    nd_act_e2_sub:        'Session de 1h 14min · 95 MB transférés',
    nd_act_e2_time:       '12:14:37',
    nd_act_e3_main:       'Pic de température détecté',
    nd_act_e3_sub:        '68°C pendant 4 min · retour à la normale',
    nd_act_e3_time:       '11:02:15',
    nd_act_e4_main:       'Agent mis à jour vers v1.0.0',
    nd_act_e4_sub:        'Mise à jour automatique depuis v0.9.4',
    nd_act_e4_time:       'hier 08:30',
    nd_act_e5_main:       'Noeud enregistré',
    nd_act_e5_sub:        "Première connexion de l'agent · token umbra_reg_a4f2...",
    nd_act_e5_time:       '11 fév.',
    nd_act_e6_main:       "thomas s'est connecté depuis Linux Desktop",
    nd_act_e6_sub:        '100.64.0.12 · IP source 91.242.18.30 · WireGuard',
    nd_act_e6_time:       'hier 16:44',
    nd_act_e7_main:       "alecptt s'est déconnecté",
    nd_act_e7_sub:        'Session de 3h 02min · 1.2 GB transférés',
    nd_act_e7_time:       'hier 11:22',
    nd_act_e8_main:       'Espace disque élevé (91%)',
    nd_act_e8_sub:        'Seuil de 90% dépassé · 2.7 GB libres',
    nd_act_e8_time:       'il y a 3j',

    // Node detail — InfoTip texts (right WG card)
    nd_wg_info_pubkey:    'Identifiant cryptographique de ce nœud dans le réseau WireGuard. Partagée avec les pairs pour établir les tunnels chiffrés.',
    nd_wg_info_peers:     'Pairs actifs sur l\'interface tailscale0, remontés par l\'agent. Avec Headscale, le serveur de coordination peut apparaître comme 1 pair dès l\'enrôlement.',
    nd_agent_info_hb:     "Signal envoyé périodiquement par l'agent au serveur pour confirmer qu'il est en ligne.",
    nd_agent_info_int:    "Fréquence à laquelle l'agent envoie ses heartbeats et remonte ses métriques.",
    nd_agent_info_au:     "L'agent se met à jour automatiquement dès qu'une nouvelle version est disponible.",
    nd_agent_info_jwt:    "Durée de validité du token d'authentification utilisé par l'agent pour communiquer avec le serveur Umbra.",

    // Node detail — config modal InfoTips

    // Node detail — info values (mock)
    nd_info_hw_value:     'Raspberry Pi 4B',
    nd_info_isp_value:    'Swisscom AG',

    // Connections page
    conn_title:        'Connexions',
    conn_sub:          'Historique des sessions VPN',
    conn_stat_today:   "Sessions aujourd'hui",
    conn_stat_vs_yesterday: 'vs hier',
    conn_stat_sessions_one: '{n} session',
    conn_stat_sessions_many: '{n} sessions',
    conn_stat_dur:     'Durée totale',
    conn_stat_dur_sub: "aujourd'hui",
    conn_stat_data:    'Données transférées',
    conn_stat_data_sub: "aujourd'hui",
    conn_stat_fav:     'Noeud favori',
    conn_filter_all:   'Toutes',
    conn_filter_active: 'Actives',
    conn_filter_ended: 'Terminées',
    conn_th_user:      'Utilisateur',
    conn_th_node:      'Noeud',
    conn_th_start:     'Début',
    conn_th_duration:  'Durée',
    conn_th_traffic:   '↑↓ Trafic',
    conn_th_ip:        'IP source',
    conn_th_status:    'Statut',
    conn_status_active: 'Active',
    conn_status_ended: 'Terminée',
    conn_duration_live: 'en cours',
    conn_empty:        'Aucune connexion',
    conn_time_today_1428: 'auj. 14:28',
    conn_time_today_1214: 'auj. 12:14',
    conn_time_today_0902: 'auj. 09:02',
    conn_time_yest_2230: 'hier 22:30',
    conn_time_yest_1811: 'hier 18:11',
    conn_time_yest_1455: 'hier 14:55',
    conn_time_yest_0800: 'hier 08:00',
    conn_time_feb22:   '22 fév.',

    // Alerts page
    alerts_title:      'Alertes',
    alerts_sub:        '{unread} non lues · {total} au total',
    alerts_mark_all:   'Tout marquer comme lu',
    alerts_filter_all: 'Toutes',
    alerts_filter_critical: 'Critiques',
    alerts_filter_warning:  'Avertiss.',
    alerts_filter_info:'Info',
    alerts_sev_critical: 'Critique',
    alerts_sev_warning:  'Avertiss.',
    alerts_sev_info:   'Info',
    alerts_empty:      'Aucune alerte',
    alerts_a1_title:   'CPU critique',
    alerts_a1_detail:  'CPU à 94% depuis plus de 10 minutes.',
    alerts_a1_time:    'il y a 3min',
    alerts_a2_title:   'Noeud hors ligne',
    alerts_a2_detail:  'macbook-pro ne répond plus depuis 2 heures.',
    alerts_a2_time:    'il y a 2h',
    alerts_a3_title:   'Température élevée',
    alerts_a3_detail:  'Température à 68°C, seuil à 85°C.',
    alerts_a3_time:    'il y a 8min',
    alerts_a4_title:   'Disque presque plein',
    alerts_a4_detail:  'Disque à 92%, espace restant : 3.8 GB.',
    alerts_a4_time:    'il y a 1h',
    alerts_a5_title:   'Latence élevée',
    alerts_a5_detail:  'Latence VPN à 280ms, pic détecté.',
    alerts_a5_time:    'il y a 3h',
    alerts_a6_title:   'Agent mis à jour',
    alerts_a6_detail:  'Agent mis à jour vers v0.2.1 avec succès.',
    alerts_a6_time:    'hier 08:30',
    alerts_a7_title:   'Nouveau pair connecté',
    alerts_a7_detail:  "thomas (Linux Desktop) s'est connecté.",
    alerts_a7_time:    'hier 14:28',

    // API keys page
    apikeys_title:     'Clés API',
    apikeys_sub_one:   '{n} clé · accès programmatique à UMBRA',
    apikeys_sub_many:  '{n} clés · accès programmatique à UMBRA',
    apikeys_new:       'Nouvelle clé',
    apikeys_th_name:   'Nom',
    apikeys_th_key:    'Clé',
    apikeys_th_perms:  'Permissions',
    apikeys_th_lastused: 'Dernière utilisation',
    apikeys_th_expires: 'Expire',
    apikeys_th_status: 'Statut',
    apikeys_status_active: 'Active',
    apikeys_status_revoked: 'Révoquée',
    apikeys_created:   'créée {when}',
    apikeys_reveal:    'Révéler',
    apikeys_hide:      'Masquer',
    apikeys_copy:      'Copier',
    apikeys_copied:    'Copié !',
    apikeys_revoke:    'Révoquer',
    apikeys_delete:    'Supprimer',
    apikeys_empty:     'Aucune clé API',
    apikeys_info:      "Les clés API permettent d'accéder à l'API UMBRA depuis vos scripts et applications. Gardez-les secrètes — elles ont les mêmes droits que votre compte.",
    apikeys_modal_title: 'Nouvelle clé API',
    apikeys_modal_name: 'Nom',
    apikeys_modal_name_ph: 'ex: script-backup, CI/CD...',
    apikeys_modal_perms: 'Permissions',
    apikeys_modal_exp: 'Expiration',
    apikeys_create_btn: 'Créer la clé',
    apikeys_exp_30:    '30 jours',
    apikeys_exp_90:    '90 jours',
    apikeys_exp_1y:    '1 an',
    apikeys_exp_never: 'Jamais',
    apikeys_just_now:  "à l'instant",
    apikeys_in:        'dans {d}',
    apikeys_never:     'jamais',
    apikeys_k1_created: 'il y a 3 mois',
    apikeys_k1_lastused:'il y a 2h',
    apikeys_k1_expires: 'dans 82j',
    apikeys_k2_created: 'il y a 1 mois',
    apikeys_k2_lastused:'il y a 1j',
    apikeys_k2_expires: 'dans 6 mois',
    apikeys_k3_created: 'il y a 6 mois',
    apikeys_k3_lastused:'il y a 3 mois',
    apikeys_k3_expires: 'expirée',

    // Onboarding
    onb_step_account:    'Compte',
    onb_step_node:       'Noeud',
    onb_step_connect:    'Connexion',
    onb_title_2:         'Configurer le premier noeud',
    onb_sub_2:           "Donnez un nom à votre machine et choisissez sa catégorie. La commande ci-dessous installe et enregistre l'agent automatiquement.",
    onb_title_3:         'Se connecter au noeud',
    onb_sub_3:           'Votre noeud est enregistré. Choisissez-le dans la liste et connectez-vous au VPN.',
    onb_node_name:       'Nom du noeud',
    onb_node_name_ph:    'RPi maison',
    onb_node_cat:        'Catégorie de machine',
    onb_cat_sbc:         'SBC',
    onb_cat_sbc_d:       'RPi, NanoPi, Orange Pi…',
    onb_cat_vps:         'VPS / Cloud',
    onb_cat_vps_d:       'Hetzner, DigitalOcean…',
    onb_cat_router:      'Routeur',
    onb_cat_router_d:    'GL.iNet, OpenWrt…',
    onb_cat_nas:         'NAS',
    onb_cat_nas_d:       'Synology, TrueNAS…',
    onb_cat_desktop:     'Desktop',
    onb_cat_desktop_d:   'Mac, Linux, PC…',
    onb_cat_other:       'Autre',
    onb_cat_other_d:     'Machine personnalisée',
    onb_cmd_copied:      'Copié',
    onb_cmd_copy:        'Copier',
    onb_cmd_comment:     '# Coller dans le terminal de votre machine',
    onb_cmd_generating:  'Génération de la commande…',
    onb_cmd_placeholder: "Entrez un nom pour générer la commande d'installation",
    onb_waiting:         "En attente de l'enregistrement de l'agent…",
    onb_platform_with:   'Plateformes : Linux amd64, arm64, armv7 · Token expire dans',
    onb_platform_without:'Plateformes : Linux amd64, arm64, armv7 · Token 1h',
    onb_token_expired:   'expiré',
    onb_err_create:      'Impossible de créer le noeud.',
    onb_err_update:      'Impossible de mettre à jour le noeud.',
    onb_success:         'est enregistré et en ligne',
    onb_next_q:          'Que voulez-vous faire maintenant ?',
    onb_next_connect:    'Se connecter au noeud',
    onb_next_connect_d:  'Établir le tunnel maintenant',
    onb_next_add:        'Ajouter un autre noeud',
    onb_next_add_d:      'VPS, routeur, NAS, SBC...',
    onb_next_invite:     'Inviter quelqu\'un',
    onb_next_invite_d:   "Partager l'accès avec la famille ou l'équipe",
    onb_next_dash:       'Aller au dashboard',
    onb_next_dash_d:     "Explorer l'interface UMBRA",
    onb_skip:            'Passer',
    onb_continue:        'Continuer →',
    onb_go_dash:         'Aller au dashboard →',

    // AddNodeModal
    addnode_title:       'Ajouter un noeud',
    addnode_sub:         "Installez l'agent UMBRA sur votre machine",
    addnode_name:        'Nom du noeud',
    addnode_name_ph:     'ex: raspi-salon',
    addnode_cat:         'Catégorie',
    addnode_cat_sbc_d:   'RPi, NanoPi…',
    addnode_cat_vps_d:   'Hetzner, OVH…',
    addnode_cat_other_d: 'Machine custom',
    addnode_platform_with: 'Linux amd64, arm64, armv7 · Token expire dans',
    addnode_platform_without: 'Linux amd64, arm64, armv7 · Token 1h',
    addnode_expired_title: 'Token expiré',
    addnode_expired_desc:  "La commande d'installation n'est plus valide.",
    addnode_regen:         'Nouveau token',
    addnode_regen_loading: 'Génération…',

    // Mobile main page
    mob_protected:       'PROTÉGÉ',
    mob_unprotected:     'NON PROTÉGÉ',
    mob_not_connected:   'Non connecté',
    mob_hero_sub:        'Sélectionne un noeud pour te protéger',
    mob_stat_upload:     'Upload',
    mob_stat_download:   'Download',
    mob_stat_latency:    'Latence',
    mob_stat_duration:   'Durée',
    mob_btn_disconnect:  'Déconnecter',
    mob_btn_reconnect:   'Reconnecter à {name}',
    mob_btn_pick:        'Choisir un noeud',
    mob_btn_change:      'Changer de noeud',
    mob_sheet_title:     'Noeuds disponibles',
    mob_sheet_active:    '{n} actifs',
    mob_tag_active:      'ACTIF',
    mob_tag_last:        'dernier',

    // Mobile settings
    mset_title:              'Paramètres',
    mset_section_account:    'Compte',
    mset_manage_sub:         "Gérer l'abonnement",
    mset_section_conn:       'Connexion',
    mset_protocol:           'Protocole',
    mset_dns:                'DNS',
    mset_dns_header:         'Serveur DNS',
    mset_kill_switch:        'Kill Switch',
    mset_kill_switch_hint:   'Coupe le réseau si la VPN se déconnecte',
    mset_auto_connect:       'Auto-connexion',
    mset_auto_connect_hint:  "Au démarrage de l'application",
    mset_split_tunnel:       'Split Tunnel',
    mset_split_tunnel_hint:  'Exclure certaines apps du VPN',
    mset_section_ui:         'Interface',
    mset_theme:              'Thème',
    mset_theme_light:        'Clair',
    mset_theme_dark:         'Sombre',
    mset_notifications:      'Notifications',
    mset_notifications_hint: 'Alertes de connexion et sécurité',
    mset_section_security:   'Sécurité',
    mset_api_keys:           'Clés API',
    mset_conn_logs:          'Journaux de connexion',
    mset_section_about:      'À propos',
    mset_docs:               'Documentation',
    mset_version:            'Version',
    mset_signout_row:        'Se déconnecter du compte',
    mset_dns_auto:           'Automatique',
    mset_dns_custom:         'Personnalisé',
    mset_sub_header:         'Abonnement',
    mset_sub_current:        'Gratuit · plan actuel',
    mset_sub_active:         'Actif',
    mset_sub_nodes:          'Noeuds',
    mset_sub_pro_feat:       '25 noeuds · 10 utilisateurs · 90j',
    mset_sub_lifetime_feat:  'Fonctionnalités Pro à vie',
    mset_sub_business_feat:  'Illimité · SSO · SLA 99,9%',
    mset_sub_business_price: 'Sur devis',
    mset_sub_see_plans:      'Voir les plans →',
    mset_api_active:         'Active',
    mset_api_revoked:        'Révoquée',
    mset_api_web_only:       'La gestion complète des clés est disponible sur la version web.',
    mset_signout_header:     'Déconnexion',
    mset_signout_title:      'Se déconnecter ?',
    mset_signout_sub:        'Tu devras te reconnecter pour accéder à UMBRA.',
    mset_signout_btn:        'Se déconnecter',
    mset_log_today_1742:     "Aujourd'hui 17:42",
    mset_log_today_1610:     "Aujourd'hui 16:10",
    mset_log_today_1405:     "Aujourd'hui 14:05",
    mset_log_hier_2318:      'Hier 23:18',
    mset_log_hier_2130:      'Hier 21:30',
    mset_log_hier_1855:      'Hier 18:55',
    mset_log_hier_1700:      'Hier 17:00',
    mset_log_feb28_0912:     '28 fév 09:12',
    mset_log_d1:             '100.64.0.1 · 3 ms',
    mset_log_d2:             'Durée 1h 28m',
    mset_log_d3:             '100.64.0.8 · 14 ms',
    mset_log_d4:             'CPU 82 % · Temp 71°C',
    mset_log_d5:             'Durée 3h 12m',
    mset_log_d6:             '100.64.0.12 · 98 ms',
    mset_log_d7:             'Durée 1h 55m',
    mset_log_d8:             '100.64.0.5 · 4 ms',

    // Alert types (from API)
    alert_type_node_offline:      'Nœud hors ligne',
    alert_type_cpu_high:          'CPU élevé',
    alert_type_memory_high:       'Mémoire élevée',
    alert_type_disk_high:         'Disque saturé',
    alert_type_temperature_high:  'Température élevée',
    alert_type_latency_high:      'Latence élevée',
    alert_type_peer_disconnected: 'Pair déconnecté',
    alert_detail_node_offline:      'Le nœud ne répond plus',
    alert_detail_cpu_high:          'CPU à {value}%',
    alert_detail_memory_high:       'Mémoire à {value}%',
    alert_detail_disk_high:         'Disque à {value}%',
    alert_detail_temperature_high:  'Température à {value}°C',
    alert_detail_latency_high:      'Latence à {value}ms',
    alert_detail_peer_disconnected: 'Pair déconnecté du mesh',

    // Error page
    err_404_title:     'Page introuvable',
    err_generic_title: 'Une erreur est survenue',
    err_404_msg:       "La page que tu cherches n'existe pas ou a été déplacée.",
    err_generic_msg:   "Quelque chose s'est mal passé.",
    err_back:          'Retour au dashboard',
  },

  en: {
    // Auth
    auth_tagline_login_1: 'Your VPN nodes,',
    auth_tagline_login_2: 'in your control.',
    auth_desc_login: 'One-command deployment. Unified interface. No third-party dependency.',
    auth_tagline_register_1: 'Ready in',
    auth_tagline_register_2: 'one command.',
    auth_desc_register: 'Create your account, add a node, connect. All in under 5 minutes.',
    auth_login_title: 'Sign in to your account',
    auth_register_title: 'Create a free account',
    auth_oauth_notice: 'OAuth available once the backend ships.',
    auth_oauth_github: 'Continue with GitHub',
    auth_oauth_google: 'Continue with Google',
    auth_or_email: 'or with email',
    auth_email: 'Email',
    auth_email_ph: 'e.g. you@example.com',
    auth_password: 'Password',
    auth_password_confirm: 'Confirm password',
    auth_password_forgot: 'Forgot password?',
    auth_password_mismatch: 'Passwords do not match',
    auth_username: 'Username',
    auth_username_ph: 'e.g. JohnDoe',
    auth_login_btn: 'Sign in →',
    auth_register_btn: 'Create account →',
    auth_no_account: 'No account yet?',
    auth_register_link: 'Free signup',
    auth_have_account: 'Already have an account?',
    auth_login_link: 'Sign in',
    auth_strength_0: '',
    auth_strength_1: 'Weak',
    auth_strength_2: 'Medium',
    auth_strength_3: 'Strong',
    auth_strength_4: 'Very strong',
    auth_err_fill: 'Fill in all fields.',
    auth_err_invalid: 'Invalid credentials.',
    auth_err_register: 'Could not create account.',
    auth_err_forgot_email: 'Enter your email to receive the reset link.',
    auth_forgot_sent: 'Reset link sent to',

    // Sidebar
    side_sub: 'VPN Manager',
    side_nav: 'Navigation',
    side_account: 'Account',
    side_dashboard: 'Dashboard',
    side_nodes: 'Nodes',
    side_connections: 'Connections',
    side_alerts: 'Alerts',
    side_api_keys: 'API keys',
    side_settings: 'Settings',
    side_account_label: 'Account',
    side_logout: 'Sign out',

    // Common
    common_back:      'Back',
    common_cancel:    'Cancel',
    common_save:      'Save',
    common_close:     'Close',
    common_delete:    'Delete',
    common_edit:      'Edit',
    common_manage:    'Manage',
    common_loading:   'Loading…',
    common_saving:    '…',
    common_soon:      'Soon',
    common_dash:      '—',
    common_just_now:  'just now',
    common_min_ago:   '{n}min ago',
    common_hour_ago:  '{n}h ago',
    common_day_ago:   '{n}d ago',
    common_label_session: 'Session',
    common_label_register: 'Sign-up',

    // Settings — page
    settings_title: 'Settings',
    settings_sub:   'Account preferences and configuration',

    // Settings — nav
    settings_nav_appearance:    'Appearance',
    settings_nav_account:       'Account',
    settings_nav_notifications: 'Notifications',
    settings_nav_security:      'Security',
    settings_nav_team:          'Team',
    settings_nav_agent:         'Agent & network',
    settings_nav_danger:        'Danger zone',

    // Settings — appearance
    settings_appearance_title:  'Appearance',
    settings_theme_label:       'Theme',
    settings_theme_sub:         'Interface colors',
    settings_theme_dark:        'Dark',
    settings_theme_light:       'Light',
    settings_lang_label:        'Language',
    settings_lang_sub:          'Interface language',

    // Settings — account
    settings_account_title:     'Account',
    settings_plan_free:         'Free',
    settings_account_name:      'Name',
    settings_account_email:     'Email',
    settings_account_password:  'Password',
    settings_account_password_sub: 'Change your password',
    settings_account_plan:      'Plan',
    settings_account_plan_sub:  'Free — 5 nodes · 1 user · 24h history',
    settings_account_view_plans: 'View plans →',

    // Settings — notifications
    settings_notif_title:    'Notifications',
    settings_notif_crit_label: 'Critical alerts',
    settings_notif_crit_sub:   'Immediate email for every critical alert',
    settings_notif_warn_label: 'Warning alerts',
    settings_notif_warn_sub:   'Email for system warnings',
    settings_notif_offline_label: 'Node offline',
    settings_notif_offline_sub:   'Notify when a node becomes unreachable',
    settings_notif_weekly_label:  'Weekly summary',
    settings_notif_weekly_sub:    'Recap report every Monday morning',
    settings_notif_update_label:  'Updates available',
    settings_notif_update_sub:    'Notify when new agent versions ship',

    // Settings — security
    settings_security_title:  'Security',
    settings_2fa_label:       'Two-factor auth',
    settings_2fa_sub:         'TOTP via app (Aegis, Bitwarden…)',
    settings_sessions_label:  'Active sessions',
    settings_sessions_sub:    'Manage your open sessions',
    settings_logs_label:      'Login logs',
    settings_logs_sub:        'Account access history',

    // Settings — team
    common_create: 'Create',
    settings_danger_nodes_sub_owned: 'Revokes the agents of your personal nodes. Organisation nodes and nodes shared with you are not affected.',
    addnode_owner: 'Owner',
    nd_action_transfer: 'Change owner',
    nd_perm_read: 'Read only',
    nd_share_add: 'Share',
    inst_nav: 'Instance',
    inst_users_one: '{n} account',
    inst_users_many: '{n} accounts',
    inst_orgs_empty: 'No organisation',
    inst_edit_user: 'Edit this account',
    inst_reset_pwd: 'Reset the password',
    inst_add_member: 'Add a member',
    inst_add_member_ph: 'Account email address',
    inst_add: 'Add',
    notif_member_added: 'Member added',
    confirm_remove_member_title: 'Remove this member',
    confirm_remove_member: 'Remove {name} from the organisation? They lose access to its nodes.',
    confirm_leave_org_title: 'Leave the organisation',
    confirm_leave_org: 'Leave "{name}"? You will lose access to its nodes.',
    confirm_leave_org_btn: 'Leave',
    inst_reset_hint: 'Pass this password to {email}. Their sessions were closed and they must change it on login.',
    org_role_owner: 'Owner',
    confirm_dissolve_org: 'Dissolve "{name}"? Its members lose the shared access. This cannot be undone.',
    confirm_suspend_user: 'Suspend {email}? They will no longer be able to sign in.',
    confirm_reset_pwd: 'Reset the password of {email}? Their current sessions will be closed.',
    inst_edit_org: 'Rename the organisation',
    inst_edit_org_hint: 'The name is what its members see. Expand the team to manage who is in it.',
    inst_orgs_one: '{n} organisation',
    inst_orgs_many: '{n} organisations',
    inst_org_delete: 'Dissolve this organisation',
    notif_org_deleted: 'Organisation dissolved',
    inst_title: 'Instance',
    inst_operator: 'operator',
    inst_stats_label: 'Accounts · organisations · nodes',
    inst_stats_sub: 'What runs on this server',
    inst_reg_label: 'Registration',
    inst_reg_sub: 'Who may create an account on this instance',
    inst_mode_open: 'Open',
    inst_mode_invite: 'Invite only',
    inst_mode_closed: 'Closed',
    inst_create_label: 'Create an account',
    inst_create_sub: 'With a temporary password to change on first login',
    inst_create: 'Create',
    inst_create_title: 'New account',
    inst_create_hint: 'The temporary password is shown only once.',
    inst_create_name: 'Name (optional)',
    inst_create_name_ph: 'First Last',
    inst_temp_hint: 'Pass this password to {email}. They will have to change it on login.',
    inst_active: 'active',
    inst_suspended: 'suspended',
    inst_suspend: 'Suspend this account',
    inst_restore: 'Restore this account',
    inst_pending_pwd: 'temp password',
    inst_nodes_one: '{n} node',
    inst_nodes_many: '{n} nodes',
    notif_inst_saved: 'Setting saved',
    notif_inst_failed: 'Change failed',
    force_pwd_title: 'Choose a password',
    force_pwd_sub: 'Your account was created with a temporary password. Replace it to continue.',
    force_pwd_current: 'Temporary password',
    force_pwd_new: 'New password',
    force_pwd_confirm: 'Confirmation',
    force_pwd_short: 'At least 8 characters',
    force_pwd_mismatch: 'Passwords do not match',
    force_pwd_submit: 'Save',
    force_pwd_saving: 'Saving…',
    force_pwd_error: 'Could not change the password',
    nd_share_org_target: 'Whole organisation',
    nd_share_email_hint: 'Enter the email address of an existing UMBRA account.',
    notif_share_done: 'Access granted',
    notif_share_failed: 'Sharing failed',
    nd_perm_connect: 'Connect',
    nd_perm_manage: 'Manage',
    nd_transfer_title: 'Change owner',
    nd_transfer_sub: "The node joins the new owner's network. Handing it to a person takes your ownership away.",
    nd_transfer_confirm: 'Transfer',
    notif_transfer_done: 'Owner changed',
    notif_transfer_failed: 'Transfer failed',
    addnode_owner_personal: 'Personal',
    addnode_owner_hint: "An organisation's node is reachable by all of its members.",
    node_org_badge: 'Org',
    org_you: 'you',
    org_pending: 'Pending',
    org_role_admin: 'Admin',
    org_role_member: 'Member',
    settings_team_create_label: 'Create an organisation',
    settings_team_create_sub: 'Share your nodes with a team, with distinct roles.',
    settings_team_create: 'Create',
    settings_team_join_label: 'Join an organisation',
    settings_team_join_sub: 'Paste the invitation code you were given.',
    settings_team_join_ph: 'umbra_invite_…',
    settings_team_join: 'Join',
    settings_team_invite: 'Invite',
    settings_team_invite_admin_only: 'Admins only',
    settings_team_plan_label: 'Members',
    settings_team_plan_sub: "People with access to the organisation's nodes",
    settings_team_members_one: '{n} member',
    settings_team_members_many: '{n} members',
    modal_create_org_title: 'New organisation',
    modal_create_org_name: 'Name',
    modal_create_org_ph: 'My team',
    modal_create_org_hint: "You will own it. The organisation's nodes form a network isolated from your own.",
    modal_invite_title: 'Invite a member',
    modal_invite_email: 'Email address',
    modal_invite_role: 'Role',
    modal_invite_send: 'Generate invitation',
    modal_invite_token_hint: 'Pass this code to {email}. It is shown once and expires in 7 days.',
    notif_org_created: 'Organisation created',
    notif_org_create_failed: 'Could not create the organisation',
    notif_org_joined: 'Joined the organisation',
    notif_org_join_failed: 'Invalid or expired invitation',
    notif_invite_failed: 'Could not send the invitation',
    notif_role_failed: 'Could not change the role',
    notif_remove_failed: 'Could not remove this member',
    settings_team_title:      'Team',
    settings_team_invite_label: 'Invite a member',
    settings_team_invite_sub:   'Shared access to organization nodes',

    // Settings — agent
    settings_agent_title:     'Agent & network',
    settings_heartbeat_label: 'Heartbeat interval',
    settings_heartbeat_sub:   'Agent reporting frequency',
    settings_autoupdate_label: 'Agent auto-update',
    settings_autoupdate_sub:   'Automatically update to the latest stable version',
    settings_subnet_label:    'Default VPN subnet',
    settings_subnet_sub:      'IP address range of the UMBRA network',
    settings_hb_1min:         '1min',
    settings_hb_5min:         '5min',

    // Settings — danger
    settings_danger_title:        'Danger zone',
    settings_danger_nodes_label:  'Delete all nodes',
    settings_danger_nodes_sub:    'Revoke all agents and remove associated data',
    settings_danger_account_label: 'Delete account',
    settings_danger_account_sub:   'Irreversible — all data will be lost',

    // Modals — edit name
    modal_edit_name_title:   'Edit name',
    modal_edit_name_label:   'Display name',
    modal_edit_name_ph:      'e.g. alec',
    modal_edit_name_err:     'Could not update name.',
    notif_name_updated:      'Name updated',

    // Modals — edit password
    modal_edit_pwd_title:    'Change password',
    modal_edit_pwd_old:      'Current password',
    modal_edit_pwd_new:      'New password',
    modal_edit_pwd_confirm:  'Confirm',
    modal_edit_pwd_err:      'Could not update password.',
    notif_pwd_updated:       'Password updated',
    notif_pwd_updated_desc:  'Your existing sessions remain active.',

    // Modals — upgrade
    modal_upgrade_title:     'Plans & pricing',
    modal_upgrade_sub:       'Pick the plan that fits your needs',
    plan_current:            'Current plan',
    plan_free_name:          'Free',
    plan_free_price:         'Free',
    plan_free_period:        'forever',
    plan_free_f1:            '5 nodes',
    plan_free_f2:            '1 user',
    plan_free_f3:            '24h history',
    plan_free_f4:            '2 API keys',
    plan_free_f5:            'Web dashboard',
    plan_free_f6:            'Community support',
    plan_pro_label:          'Recommended',
    plan_pro_name:           'Pro',
    plan_pro_price:          '€8.90',
    plan_pro_per:            '/mo',
    plan_pro_period:         'billed monthly',
    plan_pro_f1:             '25 nodes',
    plan_pro_f2:             '10 users',
    plan_pro_f3:             '90-day history',
    plan_pro_f4:             'Unlimited API keys',
    plan_pro_f5:             'Email + webhook alerts',
    plan_pro_f6:             '48h priority support',
    plan_pro_cta:            'Upgrade to Pro →',
    plan_lifetime_label:     'One-time payment',
    plan_lifetime_name:      'Lifetime',
    plan_lifetime_price:     '€149',
    plan_lifetime_period:    'pay once, keep forever',
    plan_lifetime_cta:       'Get Lifetime →',
    plan_biz_label:          'Enterprise',
    plan_biz_name:           'Business',
    plan_biz_sub:            'Pricing tailored to your organization — quote-based.',
    plan_biz_f1:             'Unlimited nodes',
    plan_biz_f2:             'Unlimited users',
    plan_biz_f3:             '1-year history',
    plan_biz_f4:             'SSO (SAML / OIDC)',
    plan_biz_f5:             'Audit logs',
    plan_biz_price:          'Custom quote',
    plan_biz_period:         'custom pricing',
    plan_biz_cta:            'Get in touch →',

    // Modals — sessions
    modal_sessions_title:    'Active sessions',
    sessions_count_one:      '{n} session',
    sessions_count_many:     '{n} sessions',
    sessions_load_err:       'Could not load sessions.',
    sessions_current_badge:  'Current',
    sessions_created:        'Created {time}',
    sessions_last_used:      'Last activity {time}',
    sessions_revoke:         'Revoke',
    sessions_revoke_others:  'Revoke all others',
    sessions_empty:          'No active sessions',
    notif_session_revoked:   'Session revoked',
    notif_session_revoke_err: 'Revoke failed',
    notif_sessions_revoked_one: '{n} session revoked',
    notif_sessions_revoked_many: '{n} sessions revoked',
    notif_sessions_revoked_desc: 'Only your current session remains active.',

    // Modals — delete nodes
    modal_delete_nodes_title: 'Delete all nodes?',
    modal_delete_nodes_warn:  'All agents will be revoked and associated data will be deleted. This action is irreversible.',
    modal_delete_nodes_btn_one:  'Delete {n} node',
    modal_delete_nodes_btn_many: 'Delete {n} nodes',
    modal_delete_nodes_progress: 'Deleting…',
    notif_nodes_deleted_one:  '{n} node deleted',
    notif_nodes_deleted_many: '{n} nodes deleted',
    notif_nodes_deleted_desc: 'All associated agents have been revoked.',
    notif_delete_failed:      'Delete failed',

    // Modals — delete account
    modal_delete_account_title: 'Delete account',
    modal_delete_account_warn:  'All your data will be permanently deleted. This action is irreversible.',
    modal_delete_account_label_pre: 'Type',
    modal_delete_account_label_post: 'to confirm',
    modal_delete_account_word: 'delete',
    modal_delete_account_btn:  'Permanently delete',
    notif_soon_title:          'Coming soon',
    notif_account_delete_soon_desc: 'Account deletion is not yet exposed by the API.',
    notif_account_deleted:          'Account deleted',

    // Login logs
    modal_login_logs_title:    'Login logs',
    login_log_action_login:    'Login',
    login_log_action_logout:   'Logout',
    login_logs_empty:          'No login history',
    sessions_on:               'on',

    // Dashboard
    dash_title:           'Dashboard',
    dash_new_node:        '+ New node',
    dash_stat_active:     'Active nodes',
    dash_stat_active_sub: '{off} offline · {warn} alert',
    dash_stat_devices:    'Devices',
    dash_stat_devices_sub: 'registered',
    dash_stat_bandwidth:  'Bandwidth',
    dash_stat_bandwidth_sub: 'today',
    dash_stat_latency:    'Avg. latency',
    dash_stat_latency_sub: 'across active nodes',
    dash_map_title:       'Node map',
    dash_map_hint:        'Click to connect',
    dash_section_nodes:   'Nodes',
    dash_view_all:        'View all ({n}) →',
    dash_empty:           'No nodes',

    // Node table headers
    node_th_node:         'Node',
    node_th_location:     'Location',
    node_th_status:       'Status',
    node_th_latency:      'Latency',
    node_th_cpu:          'CPU',

    // Map tooltip
    mtt_location:         'Location',
    mtt_latency:          'Latency',
    mtt_cpu:              'CPU',
    mtt_disconnect:       'Click to disconnect',
    mtt_offline:          'Node offline',
    mtt_pending:          'Connection pending…',
    mtt_connect:          'Click to connect',
    mtt_cluster_count:    '{n} nodes',
    mtt_view_all:         'View all nodes →',

    // Date locale
    date_locale:          'en-US',

    // Status labels
    status_online:    'Online',
    status_offline:   'Offline',
    status_warning:   'Alert',
    status_pending:   'Pending',
    status_connected: 'Connected',

    // Nodes list page
    nodes_title:        'Nodes',
    nodes_sub_one:      '{n} node registered',
    nodes_sub_many:     '{n} nodes registered',
    nodes_filter_all:   'All',
    nodes_filter_all_f: 'All',
    nodes_filter_online:    'Online',
    nodes_filter_connected: 'Connected',
    nodes_filter_warning:   'Alert',
    nodes_filter_offline:   'Offline',
    nodes_cat_sbc:     'SBC',
    nodes_cat_vps:     'VPS',
    nodes_cat_router:  'Router',
    nodes_cat_nas:     'NAS',
    nodes_cat_desktop: 'Desktop',
    nodes_cat_other:   'Other',
    nodes_empty:       'No nodes found',

    // Node detail
    nd_back:           '← Back',
    nd_loading:        'Loading…',
    nd_not_found:      'Node not found',
    nd_card_system:    'System',
    nd_card_machine:   'Machine',
    nd_card_wireguard: 'VPN network',
    nd_card_agent:     'UMBRA Agent',
    nd_card_actions:   'Actions',
    nd_metric_cpu:     'CPU',
    nd_metric_ram:     'RAM',
    nd_metric_disk:    'Disk',
    nd_metric_temp:    'Temperature',
    nd_metric_latency: 'Latency',
    nd_metric_uptime:  'Uptime',
    nd_period_1h:      '1h',
    nd_period_1d:      '1d',
    nd_period_1w:      '1w',
    nd_period_1m:      '1mo',
    nd_period_1y:      '1y',
    nd_chart_bandwidth: 'Bandwidth',
    nd_chart_latency:   'Latency',
    nd_chart_load:      'System load',
    nd_act_restart:    'Restart agent',
    nd_act_regen:      'Regenerate keys',
    nd_act_download:   'Download .conf',
    nd_act_logs:       'View logs',
    nd_act_delete:     'Delete node',
    nd_machine_model:  'Model',
    nd_machine_ram:    'RAM',
    nd_machine_os:     'OS',
    nd_machine_arch:   'Architecture',
    nd_machine_pubip:  'Public IP',
    nd_machine_loc:    'Location',
    nd_machine_isp:    'ISP',
    nd_wg_iface:       'Interface',
    nd_wg_vpnip:       'VPN IP',
    nd_wg_port:        'Port',
    nd_wg_pubkey:      'Public key',
    nd_wg_peers:       'Peers',
    nd_wg_configure:   'Configure',
    nd_wg_manage:      'Manage',
    nd_agent_version:  'Version',
    nd_agent_heartbeat: 'Last heartbeat',
    nd_agent_interval: 'Interval',
    nd_agent_autoupdate: 'Auto-update',
    nd_agent_jwt:      'JWT expires',
    nd_agent_update_avail: 'Update available',
    nd_agent_update_btn: 'Update now',
    nd_delete_title:   'Delete this node?',
    nd_delete_warn:    'The agent will be revoked and all associated data deleted. This action is irreversible.',
    nd_delete_progress: 'Deleting…',
    nd_logs_title:     'Recent logs',
    nd_logs_empty:     'No entries',
    nd_wg_save:        'Save',
    nd_peer_pubkey:    'Public key',
    nd_peer_allowed:   'AllowedIPs',
    nd_peer_endpoint:  'Endpoint',
    nd_peer_remove:    'Remove',
    notif_restart_done: 'Agent restarted',
    notif_regen_done:   'Keys regenerated',
    notif_regen_desc:   'The node must be reconnected with the new configuration.',
    notif_download_done: 'Configuration downloaded',
    notif_node_deleted: 'Node deleted',
    notif_pubkey_copied: 'Public key copied',
    notif_peer_added:   'Peer added',
    notif_peer_removed: 'Peer removed',
    nd_subtitle_sep:   ' · ',

    // Node row
    row_cut:        'Disconnect',
    row_connect:    'Connect',
    row_warn_cpu:   'CPU',

    // VPN bar
    vpn_latency:    'Latency',
    vpn_upload:     'Upload',
    vpn_download:   'Download',
    vpn_disconnect: 'Disconnect',

    // Connect modal
    conn_modal_title:       'Connect via',
    conn_modal_sub:         'Run one of these commands on the machine you want to connect.',
    conn_modal_new:         'First connection',
    conn_modal_new_hint:    '— never joined this Headscale network',
    conn_modal_switch:      'Already on this network',
    conn_modal_switch_hint: '— machine already connected to Headscale',
    conn_modal_copy:        'Copy',
    conn_modal_copied:      'Copied!',
    conn_modal_no_headscale:'Headscale not configured on this server.',
    conn_modal_note:        'Connection activates as soon as the command is run. sudo may be required on some systems.',
    conn_modal_web_notice:  'Web app — run the command in a terminal on this machine. The desktop app will automate this step.',
    conn_disconnect_toast_title: 'VPN disconnected — to deactivate the tunnel:',

    // Node detail (extras)
    nd_back_link:        '← My nodes',
    nd_share:            'Share',
    nd_connect:          'Connect',
    nd_disconnect:       'Disconnect',
    nd_metrics_title:    'System metrics',
    nd_heartbeat_ago:    'heartbeat 2s ago',
    nd_period_1h_label:  'last hour',
    nd_period_1d_label:  'last 24h',
    nd_period_1w_label:  'last week',
    nd_period_1m_label:  'last month',
    nd_period_1y_label:  'last year',
    nd_metric_memory:    'Memory',
    nd_metric_disk_label:'Disk',
    nd_metric_temp_label:'Temperature',
    nd_metric_latency_vpn: 'VPN latency',
    nd_metric_load_avg:  'load avg 0.18 · 4 cores',
    nd_metric_temp_thresh:'critical threshold: 85°C',
    nd_metric_ping:      'backend ping: 14ms',
    nd_metric_uptime_since: 'since {date}',
    nd_history_label:    'History —',
    nd_chart_cpu_ram_temp: 'CPU · Memory · Temperature',
    nd_chart_peers:      'Concurrent peers',
    nd_chart_peers_cat:  'Peers',
    nd_chart_peers_unit: '{n} peers',
    nd_action_update_to: 'Update to v{v}',
    nd_action_restarting: 'Restarting…',
    nd_action_restart:   'Restart agent',
    nd_action_view_logs: 'View logs',
    nd_action_enroll:    'Migrate node',
    nd_action_delete:    'Delete node',
    nd_enroll_title:     'Migrate to a new machine',
    nd_enroll_desc:      'Machine died or switching hardware? This token lets you reinstall the agent on a new machine. The node keeps its VPN IP, history and configuration.',
    nd_enroll_step1:     '1. Stop the current agent (if reachable)',
    nd_enroll_step1_cmd: 'sudo umbra-agent stop',
    nd_enroll_step2:     '2. On the new machine, run this command:',
    nd_enroll_token_lbl: 'Raw token (for manual install)',
    nd_enroll_copied:    'Copied!',
    nd_enroll_warn:      'Valid for 1 hour · Single use',
    nd_machine_title:    'Machine',
    nd_info_hardware:    'Hardware',
    nd_info_arch:        'Arch.',
    nd_info_pubip:       'Public IP',
    nd_info_loc:         'Location',
    nd_info_isp:         'ISP',
    nd_info_hardware_tip: 'Hardware model of the device as reported by the agent.',
    nd_info_arch_tip:    'Processor architecture (e.g. arm64, x86_64).',
    nd_info_os_tip:      'Operating system version installed on the machine.',
    nd_info_pubip_tip:   'Public IP address of the machine as seen from the internet.',
    nd_info_loc_tip:     'Approximate geolocation based on the public IP.',
    nd_info_isp_tip:     'Internet Service Provider — network operator for this machine.',
    nd_wg_iface_badge:   'tailscale0 interface',
    nd_wg_vpnip_label:   'VPN IP',
    nd_wg_pubkey_label:  'Public key',
    nd_wg_pubkey_copied: 'Copied!',
    nd_wg_pubkey_copy:   'Copy',
    nd_wg_peers_short:   '{n} active peer(s)',
    nd_agent_title:      'UMBRA Agent',
    nd_version_label:    'Version',
    nd_version_uptodate: 'up to date',
    nd_version_avail:    'v{v} available',
    nd_agent_heartbeat_label: 'Last heartbeat',
    nd_agent_heartbeat_val:   '2s ago',
    nd_agent_interval_label:  'Interval',
    nd_agent_autoupdate_label:'Auto-update',
    nd_agent_active:     'Active',
    nd_agent_inactive:   'Inactive',
    nd_agent_jwt_label:  'JWT expires',
    nd_agent_jwt_val:    'in 82d',
    nd_actions_title:    'Actions',
    nd_share_title:      'Share — {name}',
    nd_share_sub:        'Manage access to this node',
    nd_share_add_user:   'Add a user',
    nd_share_search_ph:  'Name or email...',
    nd_share_invite:     'Invite {q}',
    nd_share_invite_sub: 'Send an invitation email',
    nd_share_badge_umbra:'UMBRA',
    nd_share_badge_new:  'New',
    nd_share_default_perm:'Default permission',
    nd_share_perm_read:  'Read',
    nd_share_perm_read_d:'View metrics',
    nd_share_perm_conn:  'Connect',
    nd_share_perm_conn_d:'Connect to node',
    nd_share_perm_mgmt:  'Manage',
    nd_share_perm_mgmt_d:'Edit settings',
    nd_share_perm_admin: 'Admin',
    nd_share_perm_admin_d:'Share and revoke',
    nd_share_active:     'Active access ({n})',
    nd_share_pending:    'Pending ({n})',
    nd_share_pending_lbl:'Invitation sent · {p}',
    nd_share_empty:      'No shared access for this node',
    nd_peer_active:      'Active',
    nd_peer_inactive:    'Inactive',
    nd_logs_modal_title: 'Logs — {name}',
    nd_logs_modal_sub:   'Recent activity and events',
    nd_delete_modal_title:'Delete {name}?',
    nd_delete_modal_warn:'The node will be revoked and all its data deleted. This action is irreversible.',
    nd_delete_modal_btn: 'Permanently delete',
    nd_delete_notif_fail:'Delete failed',
    nd_state_loading:    'Loading...',
    nd_state_not_found:  'Node not found',
    nd_restart_ok:       'Agent restarted successfully',
    nd_restart_warn:     'Agent restarted — connection may be briefly unstable',
    nd_update_started:   'Update to v{v} started…',
    nd_subtitle:         '{ip}{hw}{os}{ver}',

    // Node detail — peers card
    nd_peers_card_title:  'Mesh network peers',
    nd_peers_count:       '{active} / {total} connected',
    nd_peers_th_peer:     'Peer',
    nd_peers_th_pubkey:   'Public key',
    nd_peers_th_vpnip:    'VPN IP',
    nd_peers_th_latency:  'Latency',
    nd_peers_th_traffic:  'Traffic ↑↓',
    nd_peers_th_handshake:'Handshake',
    nd_peers_th_status:   'Status',
    nd_peer_hs_4s:        '4s ago',
    nd_peer_hs_2h:        '2h ago',
    nd_peer_hs_28s:       '28s ago',
    nd_peer_hs_1min:      '1min ago',
    nd_peer_hs_Xs:        '{n}s ago',
    nd_peer_hs_Xm:        '{n}min ago',
    nd_peer_hs_Xh:        '{n}h ago',

    // Node detail — activity card
    nd_activity_title:    'Recent activity',
    nd_activity_collapse: 'Collapse ↑',
    nd_activity_view_all: 'View all →',
    nd_act_e1_main:       'alecptt connected from MacBook Pro',
    nd_act_e1_sub:        '100.64.0.10 · source IP 82.120.44.16 · WireGuard',
    nd_act_e1_time:       '14:28:04',
    nd_act_e2_main:       'marie disconnected',
    nd_act_e2_sub:        'Session of 1h 14min · 95 MB transferred',
    nd_act_e2_time:       '12:14:37',
    nd_act_e3_main:       'Temperature spike detected',
    nd_act_e3_sub:        '68°C for 4 min · back to normal',
    nd_act_e3_time:       '11:02:15',
    nd_act_e4_main:       'Agent updated to v1.0.0',
    nd_act_e4_sub:        'Auto-update from v0.9.4',
    nd_act_e4_time:       'yesterday 08:30',
    nd_act_e5_main:       'Node registered',
    nd_act_e5_sub:        'First agent connection · token umbra_reg_a4f2...',
    nd_act_e5_time:       'Feb 11',
    nd_act_e6_main:       'thomas connected from Linux Desktop',
    nd_act_e6_sub:        '100.64.0.12 · source IP 91.242.18.30 · WireGuard',
    nd_act_e6_time:       'yesterday 16:44',
    nd_act_e7_main:       'alecptt disconnected',
    nd_act_e7_sub:        'Session of 3h 02min · 1.2 GB transferred',
    nd_act_e7_time:       'yesterday 11:22',
    nd_act_e8_main:       'High disk usage (91%)',
    nd_act_e8_sub:        '90% threshold exceeded · 2.7 GB free',
    nd_act_e8_time:       '3d ago',

    // Node detail — InfoTip texts (right WG card)
    nd_wg_info_pubkey:    'Cryptographic identifier of this node in the WireGuard network. Shared with peers to establish encrypted tunnels.',
    nd_wg_info_peers:     'Active peers on the tailscale0 interface, reported by the agent. With Headscale, the coordination server may appear as 1 peer right after enrollment.',
    nd_agent_info_hb:     'Signal sent periodically by the agent to the server to confirm it is online.',
    nd_agent_info_int:    'Frequency at which the agent sends heartbeats and reports metrics.',
    nd_agent_info_au:     'The agent updates itself automatically as soon as a new version is available.',
    nd_agent_info_jwt:    'Lifetime of the auth token used by the agent to communicate with the Umbra server.',

    // Node detail — config modal InfoTips

    // Node detail — info values (mock)
    nd_info_hw_value:     'Raspberry Pi 4B',
    nd_info_isp_value:    'Swisscom AG',

    // Connections page
    conn_title:        'Connections',
    conn_sub:          'VPN session history',
    conn_stat_today:   'Sessions today',
    conn_stat_vs_yesterday: 'vs yesterday',
    conn_stat_sessions_one: '{n} session',
    conn_stat_sessions_many: '{n} sessions',
    conn_stat_dur:     'Total duration',
    conn_stat_dur_sub: 'today',
    conn_stat_data:    'Data transferred',
    conn_stat_data_sub: 'today',
    conn_stat_fav:     'Favorite node',
    conn_filter_all:   'All',
    conn_filter_active: 'Active',
    conn_filter_ended: 'Ended',
    conn_th_user:      'User',
    conn_th_node:      'Node',
    conn_th_start:     'Start',
    conn_th_duration:  'Duration',
    conn_th_traffic:   '↑↓ Traffic',
    conn_th_ip:        'Source IP',
    conn_th_status:    'Status',
    conn_status_active: 'Active',
    conn_status_ended: 'Ended',
    conn_duration_live: 'live',
    conn_empty:        'No connections',
    conn_time_today_1428: 'today 14:28',
    conn_time_today_1214: 'today 12:14',
    conn_time_today_0902: 'today 09:02',
    conn_time_yest_2230: 'yesterday 22:30',
    conn_time_yest_1811: 'yesterday 18:11',
    conn_time_yest_1455: 'yesterday 14:55',
    conn_time_yest_0800: 'yesterday 08:00',
    conn_time_feb22:   'Feb 22',

    // Alerts page
    alerts_title:      'Alerts',
    alerts_sub:        '{unread} unread · {total} total',
    alerts_mark_all:   'Mark all as read',
    alerts_filter_all: 'All',
    alerts_filter_critical: 'Critical',
    alerts_filter_warning:  'Warnings',
    alerts_filter_info:'Info',
    alerts_sev_critical: 'Critical',
    alerts_sev_warning:  'Warning',
    alerts_sev_info:   'Info',
    alerts_empty:      'No alerts',
    alerts_a1_title:   'Critical CPU',
    alerts_a1_detail:  'CPU at 94% for over 10 minutes.',
    alerts_a1_time:    '3min ago',
    alerts_a2_title:   'Node offline',
    alerts_a2_detail:  'macbook-pro has not responded for 2 hours.',
    alerts_a2_time:    '2h ago',
    alerts_a3_title:   'High temperature',
    alerts_a3_detail:  'Temperature at 68°C, threshold 85°C.',
    alerts_a3_time:    '8min ago',
    alerts_a4_title:   'Disk almost full',
    alerts_a4_detail:  'Disk at 92%, free space: 3.8 GB.',
    alerts_a4_time:    '1h ago',
    alerts_a5_title:   'High latency',
    alerts_a5_detail:  'VPN latency at 280ms, spike detected.',
    alerts_a5_time:    '3h ago',
    alerts_a6_title:   'Agent updated',
    alerts_a6_detail:  'Agent updated to v0.2.1 successfully.',
    alerts_a6_time:    'yesterday 08:30',
    alerts_a7_title:   'New peer connected',
    alerts_a7_detail:  'thomas (Linux Desktop) just connected.',
    alerts_a7_time:    'yesterday 14:28',

    // API keys page
    apikeys_title:     'API keys',
    apikeys_sub_one:   '{n} key · programmatic access to UMBRA',
    apikeys_sub_many:  '{n} keys · programmatic access to UMBRA',
    apikeys_new:       'New key',
    apikeys_th_name:   'Name',
    apikeys_th_key:    'Key',
    apikeys_th_perms:  'Permissions',
    apikeys_th_lastused: 'Last used',
    apikeys_th_expires: 'Expires',
    apikeys_th_status: 'Status',
    apikeys_status_active: 'Active',
    apikeys_status_revoked: 'Revoked',
    apikeys_created:   'created {when}',
    apikeys_reveal:    'Reveal',
    apikeys_hide:      'Hide',
    apikeys_copy:      'Copy',
    apikeys_copied:    'Copied!',
    apikeys_revoke:    'Revoke',
    apikeys_delete:    'Delete',
    apikeys_empty:     'No API keys',
    apikeys_info:      'API keys grant access to the UMBRA API from your scripts and applications. Keep them secret — they have the same rights as your account.',
    apikeys_modal_title: 'New API key',
    apikeys_modal_name: 'Name',
    apikeys_modal_name_ph: 'e.g. script-backup, CI/CD...',
    apikeys_modal_perms: 'Permissions',
    apikeys_modal_exp: 'Expiration',
    apikeys_create_btn: 'Create key',
    apikeys_exp_30:    '30 days',
    apikeys_exp_90:    '90 days',
    apikeys_exp_1y:    '1 year',
    apikeys_exp_never: 'Never',
    apikeys_just_now:  'just now',
    apikeys_in:        'in {d}',
    apikeys_never:     'never',
    apikeys_k1_created: '3 months ago',
    apikeys_k1_lastused:'2h ago',
    apikeys_k1_expires: 'in 82d',
    apikeys_k2_created: '1 month ago',
    apikeys_k2_lastused:'1d ago',
    apikeys_k2_expires: 'in 6 months',
    apikeys_k3_created: '6 months ago',
    apikeys_k3_lastused:'3 months ago',
    apikeys_k3_expires: 'expired',

    // Onboarding
    onb_step_account:    'Account',
    onb_step_node:       'Node',
    onb_step_connect:    'Connection',
    onb_title_2:         'Set up the first node',
    onb_sub_2:           'Give your machine a name and pick its category. The command below installs and registers the agent automatically.',
    onb_title_3:         'Connect to the node',
    onb_sub_3:           'Your node is registered. Pick it from the list and connect to the VPN.',
    onb_node_name:       'Node name',
    onb_node_name_ph:    'home-rpi',
    onb_node_cat:        'Machine category',
    onb_cat_sbc:         'SBC',
    onb_cat_sbc_d:       'RPi, NanoPi, Orange Pi…',
    onb_cat_vps:         'VPS / Cloud',
    onb_cat_vps_d:       'Hetzner, DigitalOcean…',
    onb_cat_router:      'Router',
    onb_cat_router_d:    'GL.iNet, OpenWrt…',
    onb_cat_nas:         'NAS',
    onb_cat_nas_d:       'Synology, TrueNAS…',
    onb_cat_desktop:     'Desktop',
    onb_cat_desktop_d:   'Mac, Linux, PC…',
    onb_cat_other:       'Other',
    onb_cat_other_d:     'Custom machine',
    onb_cmd_copied:      'Copied',
    onb_cmd_copy:        'Copy',
    onb_cmd_comment:     '# Paste in your machine terminal',
    onb_cmd_generating:  'Generating command…',
    onb_cmd_placeholder: 'Enter a name to generate the install command',
    onb_waiting:         'Waiting for the agent to register…',
    onb_platform_with:   'Platforms: Linux amd64, arm64, armv7 · Token expires in',
    onb_platform_without:'Platforms: Linux amd64, arm64, armv7 · Token 1h',
    onb_token_expired:   'expired',
    onb_err_create:      'Could not create the node.',
    onb_err_update:      'Could not update the node.',
    onb_success:         'is registered and online',
    onb_next_q:          'What do you want to do next?',
    onb_next_connect:    'Connect to the node',
    onb_next_connect_d:  'Establish the tunnel now',
    onb_next_add:        'Add another node',
    onb_next_add_d:      'VPS, router, NAS, SBC...',
    onb_next_invite:     'Invite someone',
    onb_next_invite_d:   'Share access with family or team',
    onb_next_dash:       'Go to the dashboard',
    onb_next_dash_d:     'Explore the UMBRA interface',
    onb_skip:            'Skip',
    onb_continue:        'Continue →',
    onb_go_dash:         'Go to the dashboard →',

    // AddNodeModal
    addnode_title:       'Add a node',
    addnode_sub:         'Install the UMBRA agent on your machine',
    addnode_name:        'Node name',
    addnode_name_ph:     'e.g. living-room-rpi',
    addnode_cat:         'Category',
    addnode_cat_sbc_d:   'RPi, NanoPi…',
    addnode_cat_vps_d:   'Hetzner, OVH…',
    addnode_cat_other_d: 'Custom machine',
    addnode_platform_with: 'Linux amd64, arm64, armv7 · Token expires in',
    addnode_platform_without: 'Linux amd64, arm64, armv7 · Token 1h',
    addnode_expired_title: 'Token expired',
    addnode_expired_desc:  'The install command is no longer valid.',
    addnode_regen:         'New token',
    addnode_regen_loading: 'Generating…',

    // Mobile main page
    mob_protected:       'PROTECTED',
    mob_unprotected:     'UNPROTECTED',
    mob_not_connected:   'Not connected',
    mob_hero_sub:        'Select a node to protect yourself',
    mob_stat_upload:     'Upload',
    mob_stat_download:   'Download',
    mob_stat_latency:    'Latency',
    mob_stat_duration:   'Duration',
    mob_btn_disconnect:  'Disconnect',
    mob_btn_reconnect:   'Reconnect to {name}',
    mob_btn_pick:        'Choose a node',
    mob_btn_change:      'Change node',
    mob_sheet_title:     'Available nodes',
    mob_sheet_active:    '{n} active',
    mob_tag_active:      'ACTIVE',
    mob_tag_last:        'last',

    // Mobile settings
    mset_title:              'Settings',
    mset_section_account:    'Account',
    mset_manage_sub:         'Manage subscription',
    mset_section_conn:       'Connection',
    mset_protocol:           'Protocol',
    mset_dns:                'DNS',
    mset_dns_header:         'DNS Server',
    mset_kill_switch:        'Kill Switch',
    mset_kill_switch_hint:   'Cuts the network if VPN disconnects',
    mset_auto_connect:       'Auto-connect',
    mset_auto_connect_hint:  'On application startup',
    mset_split_tunnel:       'Split Tunnel',
    mset_split_tunnel_hint:  'Exclude certain apps from VPN',
    mset_section_ui:         'Interface',
    mset_theme:              'Theme',
    mset_theme_light:        'Light',
    mset_theme_dark:         'Dark',
    mset_notifications:      'Notifications',
    mset_notifications_hint: 'Connection and security alerts',
    mset_section_security:   'Security',
    mset_api_keys:           'API Keys',
    mset_conn_logs:          'Connection logs',
    mset_section_about:      'About',
    mset_docs:               'Documentation',
    mset_version:            'Version',
    mset_signout_row:        'Sign out',
    mset_dns_auto:           'Automatic',
    mset_dns_custom:         'Custom',
    mset_sub_header:         'Subscription',
    mset_sub_current:        'Free · current plan',
    mset_sub_active:         'Active',
    mset_sub_nodes:          'Nodes',
    mset_sub_pro_feat:       '25 nodes · 10 users · 90d',
    mset_sub_lifetime_feat:  'Pro features for life',
    mset_sub_business_feat:  'Unlimited · SSO · SLA 99.9%',
    mset_sub_business_price: 'On request',
    mset_sub_see_plans:      'View plans →',
    mset_api_active:         'Active',
    mset_api_revoked:        'Revoked',
    mset_api_web_only:       'Full key management is available on the web version.',
    mset_signout_header:     'Sign out',
    mset_signout_title:      'Sign out?',
    mset_signout_sub:        'You will need to sign in again to access UMBRA.',
    mset_signout_btn:        'Sign out',
    mset_log_today_1742:     'Today 17:42',
    mset_log_today_1610:     'Today 16:10',
    mset_log_today_1405:     'Today 14:05',
    mset_log_hier_2318:      'Yesterday 23:18',
    mset_log_hier_2130:      'Yesterday 21:30',
    mset_log_hier_1855:      'Yesterday 18:55',
    mset_log_hier_1700:      'Yesterday 17:00',
    mset_log_feb28_0912:     'Feb 28 09:12',
    mset_log_d1:             '100.64.0.1 · 3 ms',
    mset_log_d2:             'Duration 1h 28m',
    mset_log_d3:             '100.64.0.8 · 14 ms',
    mset_log_d4:             'CPU 82 % · Temp 71°C',
    mset_log_d5:             'Duration 3h 12m',
    mset_log_d6:             '100.64.0.12 · 98 ms',
    mset_log_d7:             'Duration 1h 55m',
    mset_log_d8:             '100.64.0.5 · 4 ms',

    // Alert types (from API)
    alert_type_node_offline:      'Node offline',
    alert_type_cpu_high:          'High CPU',
    alert_type_memory_high:       'High memory',
    alert_type_disk_high:         'Disk full',
    alert_type_temperature_high:  'High temperature',
    alert_type_latency_high:      'High latency',
    alert_type_peer_disconnected: 'Peer disconnected',
    alert_detail_node_offline:      'The node is no longer responding',
    alert_detail_cpu_high:          'CPU at {value}%',
    alert_detail_memory_high:       'Memory at {value}%',
    alert_detail_disk_high:         'Disk at {value}%',
    alert_detail_temperature_high:  'Temperature at {value}°C',
    alert_detail_latency_high:      'Latency at {value}ms',
    alert_detail_peer_disconnected: 'Peer disconnected from the mesh',

    // Error page
    err_404_title:     'Page not found',
    err_generic_title: 'An error occurred',
    err_404_msg:       "The page you're looking for doesn't exist or has been moved.",
    err_generic_msg:   'Something went wrong.',
    err_back:          'Back to dashboard',
  },
}

export function useT() {
  const cookie = useCookie<Lang>('umbra-lang', {
    default: () => 'fr',
    maxAge: 60 * 60 * 24 * 365,
    sameSite: 'lax',
  })
  const lang = useState<Lang>('umbra-lang', () => cookie.value || 'fr')

  function setLang(l: Lang) {
    lang.value = l
    cookie.value = l
  }

  function t(key: string, vars?: Record<string, string | number>): string {
    let s = TR[lang.value]?.[key] ?? TR.fr[key] ?? key
    if (vars) {
      for (const k in vars) s = s.replace(new RegExp(`\\{${k}\\}`, 'g'), String(vars[k]))
    }
    return s
  }

  return { lang, setLang, t }
}
