/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AgentTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'expiresAt', 'id', 'nodeId', 'nodeName', 'previousTokenHash', 'targetOrgId', 'tokenHash', 'usedAt'] as const
  $columns = AgentTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nodeId: string | null
  @column()
  declare nodeName: string | null
  @column()
  declare previousTokenHash: string | null
  @column()
  declare targetOrgId: string | null
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'keyHash', 'keyPrefix', 'lastUsedAt', 'name', 'orgId', 'revokedAt', 'scopes', 'userId'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyHash: string
  @column()
  declare keyPrefix: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare orgId: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare scopes: any
  @column()
  declare userId: string
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'id', 'ipAddress', 'newValue', 'oldValue', 'orgId', 'performedBy', 'resourceId', 'resourceType', 'userAgent'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare newValue: any | null
  @column()
  declare oldValue: any | null
  @column()
  declare orgId: string | null
  @column()
  declare performedBy: string
  @column()
  declare resourceId: string
  @column()
  declare resourceType: string
  @column()
  declare userAgent: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuthSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'ipAddress', 'refreshToken', 'revokedAt', 'userAgent', 'userId'] as const
  $columns = AuthSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare refreshToken: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class ConnectionLogSchema extends BaseModel {
  static $columns = ['bytesReceived', 'bytesSent', 'clientIp', 'connectedAt', 'deviceId', 'disconnectedAt', 'headscalePreauthKey', 'id', 'lastPeerBytesReceived', 'lastPeerBytesSent', 'nodeId', 'protocol', 'userId'] as const
  $columns = ConnectionLogSchema.$columns
  @column()
  declare bytesReceived: bigint | number | null
  @column()
  declare bytesSent: bigint | number | null
  @column()
  declare clientIp: string | null
  @column.dateTime()
  declare connectedAt: DateTime
  @column()
  declare deviceId: string | null
  @column.dateTime()
  declare disconnectedAt: DateTime | null
  @column()
  declare headscalePreauthKey: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastPeerBytesReceived: bigint | number | null
  @column()
  declare lastPeerBytesSent: bigint | number | null
  @column()
  declare nodeId: string
  @column()
  declare protocol: string | null
  @column()
  declare userId: string
}

export class DeviceSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'headscaleId', 'id', 'isActive', 'lastSeenAt', 'name', 'type', 'updatedAt', 'userId', 'wireguardIp', 'wireguardPubkey'] as const
  $columns = DeviceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare headscaleId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare wireguardIp: string | null
  @column()
  declare wireguardPubkey: string | null
}

export class InstanceSettingSchema extends BaseModel {
  static $columns = ['id', 'registrationMode', 'updatedAt'] as const
  $columns = InstanceSettingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare registrationMode: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'id', 'invitedBy', 'nodeId', 'orgId', 'permission', 'role', 'tokenHash'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invitedBy: string
  @column()
  declare nodeId: string | null
  @column()
  declare orgId: string | null
  @column()
  declare permission: string | null
  @column()
  declare role: string | null
  @column()
  declare tokenHash: string
}

export class NodeAlertSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'id', 'isActive', 'nodeId', 'notifyEmail', 'notifyWebhook', 'resolvedAt', 'thresholdUnit', 'thresholdValue', 'triggeredAt', 'type', 'updatedAt'] as const
  $columns = NodeAlertSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare nodeId: string
  @column()
  declare notifyEmail: boolean
  @column()
  declare notifyWebhook: string | null
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare thresholdUnit: string | null
  @column()
  declare thresholdValue: string | null
  @column.dateTime()
  declare triggeredAt: DateTime | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NodeMemberSchema extends BaseModel {
  static $columns = ['grantedAt', 'grantedBy', 'id', 'nodeId', 'orgId', 'permission', 'userId'] as const
  $columns = NodeMemberSchema.$columns
  @column.dateTime()
  declare grantedAt: DateTime
  @column()
  declare grantedBy: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nodeId: string
  @column()
  declare orgId: string | null
  @column()
  declare permission: string
  @column()
  declare userId: string | null
}

export class NodeMetricSchema extends BaseModel {
  static $columns = ['activePeers', 'bytesReceived', 'bytesSent', 'cpuCores', 'cpuPercent', 'diskPercent', 'diskTotalGb', 'latencyMs', 'loadAvg', 'memTotalGb', 'memoryPercent', 'nodeId', 'recordedAt', 'temperatureCelsius', 'uptimeSeconds'] as const
  $columns = NodeMetricSchema.$columns
  @column()
  declare activePeers: number | null
  @column()
  declare bytesReceived: bigint | number | null
  @column()
  declare bytesSent: bigint | number | null
  @column()
  declare cpuCores: number | null
  @column()
  declare cpuPercent: string | null
  @column()
  declare diskPercent: string | null
  @column()
  declare diskTotalGb: number | null
  @column()
  declare latencyMs: number | null
  @column()
  declare loadAvg: number | null
  @column()
  declare memTotalGb: number | null
  @column()
  declare memoryPercent: string | null
  @column()
  declare nodeId: string
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare temperatureCelsius: string | null
  @column()
  declare uptimeSeconds: bigint | number | null
}

export class NodePeerStatSchema extends BaseModel {
  static $columns = ['allowedIps', 'bytesReceived', 'bytesSent', 'endpoint', 'id', 'isActive', 'lastHandshakeAt', 'nodeId', 'peerName', 'peerPubkey', 'updatedAt'] as const
  $columns = NodePeerStatSchema.$columns
  @column()
  declare allowedIps: any | null
  @column()
  declare bytesReceived: bigint | number | null
  @column()
  declare bytesSent: bigint | number | null
  @column()
  declare endpoint: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastHandshakeAt: DateTime | null
  @column()
  declare nodeId: string
  @column()
  declare peerName: string | null
  @column()
  declare peerPubkey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NodeSchema extends BaseModel {
  static $columns = ['agentVersion', 'arch', 'category', 'city', 'countryCode', 'createdAt', 'deletedAt', 'hardwareModel', 'headscaleId', 'hostname', 'id', 'ipAddress', 'lastSeenAt', 'latitude', 'longitude', 'name', 'openvpnPort', 'osVersion', 'ownerOrgId', 'ownerUserId', 'status', 'supportsOpenvpn', 'supportsWireguard', 'updatedAt', 'wireguardIp', 'wireguardPort', 'wireguardPubkey'] as const
  $columns = NodeSchema.$columns
  @column()
  declare agentVersion: string | null
  @column()
  declare arch: string | null
  @column()
  declare category: string
  @column()
  declare city: string | null
  @column()
  declare countryCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare hardwareModel: string | null
  @column()
  declare headscaleId: string | null
  @column()
  declare hostname: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare name: string
  @column()
  declare openvpnPort: number | null
  @column()
  declare osVersion: string | null
  @column()
  declare ownerOrgId: string | null
  @column()
  declare ownerUserId: string | null
  @column()
  declare status: string
  @column()
  declare supportsOpenvpn: boolean
  @column()
  declare supportsWireguard: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wireguardIp: string | null
  @column()
  declare wireguardPort: number | null
  @column()
  declare wireguardPubkey: string | null
}

export class OrgMemberSchema extends BaseModel {
  static $columns = ['id', 'joinedAt', 'orgId', 'role', 'userId'] as const
  $columns = OrgMemberSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare orgId: string
  @column()
  declare role: string
  @column()
  declare userId: string
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'plan', 'slug', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare plan: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'deletedAt', 'email', 'emailVerified', 'exitNodeId', 'githubId', 'googleId', 'id', 'instanceRole', 'isActive', 'mustChangePassword', 'name', 'passwordHash', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare emailVerified: boolean
  @column()
  declare exitNodeId: string | null
  @column()
  declare githubId: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare instanceRole: string
  @column()
  declare isActive: boolean
  @column()
  declare mustChangePassword: boolean
  @column()
  declare name: string | null
  @column()
  declare passwordHash: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
